CREATE TABLE control_measure_code
(
  code      	VARCHAR(20) PRIMARY KEY,
  description  	VARCHAR(200)
);

INSERT INTO control_measure_code (code, description) VALUES ('1','Wet Scrubber - High Efficiency');
INSERT INTO control_measure_code (code, description) VALUES ('2','Wet Scrubber - Medium Efficiency');
INSERT INTO control_measure_code (code, description) VALUES ('3','Wet Scrubber - Low Efficiency');
INSERT INTO control_measure_code (code, description) VALUES ('4','Gravity Collector - High Efficiency');
INSERT INTO control_measure_code (code, description) VALUES ('6','Gravity Collector - Low Efficiency');
INSERT INTO control_measure_code (code, description) VALUES ('7','Centrifugal Collector (Cyclone) - High Efficiency');
INSERT INTO control_measure_code (code, description) VALUES ('8','Centrifugal Collector (Cyclone) - Medium Efficiency');
INSERT INTO control_measure_code (code, description) VALUES ('9','Centrifugal Collector (Cyclone) - Low Efficiency');
INSERT INTO control_measure_code (code, description) VALUES ('10','Electrostatic Precipitator - High Efficiency');
INSERT INTO control_measure_code (code, description) VALUES ('11','Electrostatic Precipitator - Medium Efficiency');
INSERT INTO control_measure_code (code, description) VALUES ('13','Gas Scrubber (General, Not Classified)');
INSERT INTO control_measure_code (code, description) VALUES ('14','Mist Eliminator - High Velocity, I.E. V>250 Ft/Min.');
INSERT INTO control_measure_code (code, description) VALUES ('15','Mist Eliminator - Low Velocity, I.E. V<250 Ft/Min.');
INSERT INTO control_measure_code (code, description) VALUES ('16','Fabric Filter - High Temperature, I.E. T>250F');
INSERT INTO control_measure_code (code, description) VALUES ('17','Fabric Filter - Medium Temperature, I.E. 180F<T<250F');
INSERT INTO control_measure_code (code, description) VALUES ('18','Fabric Filter - Low Temperature , I.E. T<180F');
INSERT INTO control_measure_code (code, description) VALUES ('19','Catalytic Afterburner');
INSERT INTO control_measure_code (code, description) VALUES ('20','Catalytic Afterburner with Heat Exchanger');
INSERT INTO control_measure_code (code, description) VALUES ('21','Direct Flame Afterburner');
INSERT INTO control_measure_code (code, description) VALUES ('22','Direct Flame Afterburner with Heat Exchanger');
INSERT INTO control_measure_code (code, description) VALUES ('23','Flaring');
INSERT INTO control_measure_code (code, description) VALUES ('24','Modified Burner or Furnace Design');
INSERT INTO control_measure_code (code, description) VALUES ('25','Staged combustion');
INSERT INTO control_measure_code (code, description) VALUES ('26','Flue Gas Recirculation');
INSERT INTO control_measure_code (code, description) VALUES ('27','Reduced Combustion - Air Preheating');
INSERT INTO control_measure_code (code, description) VALUES ('28','Steam or Water Injection');
INSERT INTO control_measure_code (code, description) VALUES ('29','Low Excess Air Firing');
INSERT INTO control_measure_code (code, description) VALUES ('31','Air Injection');
INSERT INTO control_measure_code (code, description) VALUES ('32','Ammonia Injection');
INSERT INTO control_measure_code (code, description) VALUES ('33','Control of % O2 in Combustion Air (Off Stoichiometric Firing)');
INSERT INTO control_measure_code (code, description) VALUES ('34','Wellman-Lord/Sodium Sulfite Scrubbing');
INSERT INTO control_measure_code (code, description) VALUES ('35','Magnesium Oxide Scrubbing');
INSERT INTO control_measure_code (code, description) VALUES ('36','Dual Alkali Scrubbing');
INSERT INTO control_measure_code (code, description) VALUES ('37','Citrate Process Scrubbing');
INSERT INTO control_measure_code (code, description) VALUES ('38','Ammonia Scrubbing');
INSERT INTO control_measure_code (code, description) VALUES ('39','Catalytic Oxidation - Flue Gas Desulfurization');
INSERT INTO control_measure_code (code, description) VALUES ('40','Alkalized Alumina');
INSERT INTO control_measure_code (code, description) VALUES ('41','Dry Limestone Injection');
INSERT INTO control_measure_code (code, description) VALUES ('42','Wet Limestone Injection');
INSERT INTO control_measure_code (code, description) VALUES ('43','Sulfuric Acid Plant - Contact Process');
INSERT INTO control_measure_code (code, description) VALUES ('44','Sulfuric Acid Plant - Double Contact Process');
INSERT INTO control_measure_code (code, description) VALUES ('45','Sulfur Plant');
INSERT INTO control_measure_code (code, description) VALUES ('46','Process Change');
INSERT INTO control_measure_code (code, description) VALUES ('47','Vapor Recovery System (Including Condensers, Hooding, Other Enclosures)');
INSERT INTO control_measure_code (code, description) VALUES ('48','Adsorption - Activated Carbon or other');
INSERT INTO control_measure_code (code, description) VALUES ('49','Liquid Filtration System');
INSERT INTO control_measure_code (code, description) VALUES ('50','Packed-Gas Absorption Column');
INSERT INTO control_measure_code (code, description) VALUES ('51','Tray-Type Gas Absorption Column');
INSERT INTO control_measure_code (code, description) VALUES ('52','Spray Tower');
INSERT INTO control_measure_code (code, description) VALUES ('54','Process Enclosed');
INSERT INTO control_measure_code (code, description) VALUES ('55','Impingement Plate Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('56','Dynamic Separator (Dry)');
INSERT INTO control_measure_code (code, description) VALUES ('57','Dynamic Separator (wet)');
INSERT INTO control_measure_code (code, description) VALUES ('58','Mat or Panel Filter');
INSERT INTO control_measure_code (code, description) VALUES ('59','Metal Fabric Filter Screen (Cotton Gins)');
INSERT INTO control_measure_code (code, description) VALUES ('60','Process Gas Recovery');
INSERT INTO control_measure_code (code, description) VALUES ('61','Dust Suppression by Water Sprays');
INSERT INTO control_measure_code (code, description) VALUES ('62','Dust Suppression by Chemical Stabilizers or Wetting Agents');
INSERT INTO control_measure_code (code, description) VALUES ('63','Gravel Bed Filter');
INSERT INTO control_measure_code (code, description) VALUES ('64','Annular Ring Filter');
INSERT INTO control_measure_code (code, description) VALUES ('65','Catalytic Reduction');
INSERT INTO control_measure_code (code, description) VALUES ('66','Molecular Sieve');
INSERT INTO control_measure_code (code, description) VALUES ('67','Wet Lime Slurry Scrubbing');
INSERT INTO control_measure_code (code, description) VALUES ('68','Alkaline Fly Ash Scrubbing');
INSERT INTO control_measure_code (code, description) VALUES ('69','Sodium Carbonate Scrubbing');
INSERT INTO control_measure_code (code, description) VALUES ('72','Tube and Shell Condenser');
INSERT INTO control_measure_code (code, description) VALUES ('73','Refrigerated Condenser');
INSERT INTO control_measure_code (code, description) VALUES ('74','Barometric Condenser');
INSERT INTO control_measure_code (code, description) VALUES ('75','Cyclone / Centrifugal Collector');
INSERT INTO control_measure_code (code, description) VALUES ('76','Multiple Cyclone w/o Fly Ash Reinjection');
INSERT INTO control_measure_code (code, description) VALUES ('79','Dry Electrostatic Granular Filter (DEGF)');
INSERT INTO control_measure_code (code, description) VALUES ('81','Chemical Reduction');
INSERT INTO control_measure_code (code, description) VALUES ('82','Ozonation');
INSERT INTO control_measure_code (code, description) VALUES ('83','Chemical Neutralization');
INSERT INTO control_measure_code (code, description) VALUES ('84','Activated Clay Adsorption');
INSERT INTO control_measure_code (code, description) VALUES ('86','Water Curtain');
INSERT INTO control_measure_code (code, description) VALUES ('87','Nitrogen Blanket');
INSERT INTO control_measure_code (code, description) VALUES ('88','Conservation Vent');
INSERT INTO control_measure_code (code, description) VALUES ('89','Bottom Filling');
INSERT INTO control_measure_code (code, description) VALUES ('91','Conversion to Floating Roof Tank');
INSERT INTO control_measure_code (code, description) VALUES ('92','Conversion to Pressurized Tank');
INSERT INTO control_measure_code (code, description) VALUES ('93','Submerged Filling');
INSERT INTO control_measure_code (code, description) VALUES ('94','Underground Tank');
INSERT INTO control_measure_code (code, description) VALUES ('95','White Paint');
INSERT INTO control_measure_code (code, description) VALUES ('96','Vapor Lock Balance Recovery System');
INSERT INTO control_measure_code (code, description) VALUES ('97','Secondary Seal on Floating Roof Tank');
INSERT INTO control_measure_code (code, description) VALUES ('98','Moving Bed Dry Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('100','Baghouse');
INSERT INTO control_measure_code (code, description) VALUES ('101','High-Efficiency Particulate Air Filter (HEPA)');
INSERT INTO control_measure_code (code, description) VALUES ('102','Low Solvent Coatings');
INSERT INTO control_measure_code (code, description) VALUES ('103','Powder Coatings');
INSERT INTO control_measure_code (code, description) VALUES ('104','Waterborne Coatings');
INSERT INTO control_measure_code (code, description) VALUES ('105','Process Modification - Electrostatic Spraying');
INSERT INTO control_measure_code (code, description) VALUES ('106','Dust Suppression by Physical Stabilization');
INSERT INTO control_measure_code (code, description) VALUES ('107','Selective Noncatalytic Reduction for NOx');
INSERT INTO control_measure_code (code, description) VALUES ('108','Dust Suppression - Traffic Control');
INSERT INTO control_measure_code (code, description) VALUES ('109','Catalytic Oxidizer / Incinerator');
INSERT INTO control_measure_code (code, description) VALUES ('110','Vapor Recovery Unit');
INSERT INTO control_measure_code (code, description) VALUES ('112','Afterburner');
INSERT INTO control_measure_code (code, description) VALUES ('113','Rotoclone');
INSERT INTO control_measure_code (code, description) VALUES ('115','Impingement Type Wet Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('116','Catalytic Incinerator');
INSERT INTO control_measure_code (code, description) VALUES ('118','Crossflow Packed Bed');
INSERT INTO control_measure_code (code, description) VALUES ('119','Dry Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('120','Floating Bed Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('121','Cyclones (Multiple)');
INSERT INTO control_measure_code (code, description) VALUES ('122','Quench Tower');
INSERT INTO control_measure_code (code, description) VALUES ('123','Spray Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('124','High Pressure Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('127','Fabric Filter / Baghouse');
INSERT INTO control_measure_code (code, description) VALUES ('128','Electrostatic Precipitator - Dry (DESP)');
INSERT INTO control_measure_code (code, description) VALUES ('129','Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('130','Caustic Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('131','Thermal Oxidizer');
INSERT INTO control_measure_code (code, description) VALUES ('132','Condenser');
INSERT INTO control_measure_code (code, description) VALUES ('134','Demister');
INSERT INTO control_measure_code (code, description) VALUES ('137','HVAF');
INSERT INTO control_measure_code (code, description) VALUES ('138','Boiler at Landfill');
INSERT INTO control_measure_code (code, description) VALUES ('139','Selective Catalytic Reduction (SCR)');
INSERT INTO control_measure_code (code, description) VALUES ('140','Selective Non-catalytic Reduction (SNCR)');
INSERT INTO control_measure_code (code, description) VALUES ('141','Wet Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('143','Wet Suppression');
INSERT INTO control_measure_code (code, description) VALUES ('144','Spray Screen');
INSERT INTO control_measure_code (code, description) VALUES ('145','Single Wet Cap');
INSERT INTO control_measure_code (code, description) VALUES ('146','Electrostatic Precipitator - Wet  (WESP)');
INSERT INTO control_measure_code (code, description) VALUES ('147','Increased Air/Fuel Ratio with Intercooling');
INSERT INTO control_measure_code (code, description) VALUES ('148','Clean Burn');
INSERT INTO control_measure_code (code, description) VALUES ('149','Pre-Combustion Chamber');
INSERT INTO control_measure_code (code, description) VALUES ('150','Mechanical Collector');
INSERT INTO control_measure_code (code, description) VALUES ('151','Fiber Mist Eliminator');
INSERT INTO control_measure_code (code, description) VALUES ('153','Water Sprays');
INSERT INTO control_measure_code (code, description) VALUES ('154','Screened Drums or Cages');
INSERT INTO control_measure_code (code, description) VALUES ('155','Packed Bed Scrubber - High Efficiency');
INSERT INTO control_measure_code (code, description) VALUES ('157','Screen');
INSERT INTO control_measure_code (code, description) VALUES ('158','Ionizing Wet Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('159','Electrified Filter Bed');
INSERT INTO control_measure_code (code, description) VALUES ('201','Knock Out Box');
INSERT INTO control_measure_code (code, description) VALUES ('202','Spray Dryer Adsorber (SDA)');
INSERT INTO control_measure_code (code, description) VALUES ('203','Catalytic Converter');
INSERT INTO control_measure_code (code, description) VALUES ('204','Overfire Air');
INSERT INTO control_measure_code (code, description) VALUES ('205','Low NOx Burner (LNB)');
INSERT INTO control_measure_code (code, description) VALUES ('206','Dry Sorbent Injection (DSI, other than ACI)');
INSERT INTO control_measure_code (code, description) VALUES ('207','Activated Carbon Injection (ACI)');
INSERT INTO control_measure_code (code, description) VALUES ('208','Freeboard Refrigeration Device');
INSERT INTO control_measure_code (code, description) VALUES ('209','Gravity Collector');
INSERT INTO control_measure_code (code, description) VALUES ('210','Centrifugal Collector');
INSERT INTO control_measure_code (code, description) VALUES ('211','Mist Eliminator');
INSERT INTO control_measure_code (code, description) VALUES ('212','Steam Injection');
INSERT INTO control_measure_code (code, description) VALUES ('213','Water Injection');
INSERT INTO control_measure_code (code, description) VALUES ('214','Low Nitrogen Content Fuel');
INSERT INTO control_measure_code (code, description) VALUES ('215','Flue Gas Desulfurization (FGD)');
INSERT INTO control_measure_code (code, description) VALUES ('216','Sulfuric Acid Plant');
INSERT INTO control_measure_code (code, description) VALUES ('217','Dust Suppression');
INSERT INTO control_measure_code (code, description) VALUES ('218','Electrostatic Spraying');
INSERT INTO control_measure_code (code, description) VALUES ('219','Increased Monitoring Frequency (IMF) of PM Controls');
INSERT INTO control_measure_code (code, description) VALUES ('133','Thermal Oxidizer / Incinerator');
INSERT INTO control_measure_code (code, description) VALUES ('70','Sodium-Alkali Scrubbing');
INSERT INTO control_measure_code (code, description) VALUES ('78','Baffle');
INSERT INTO control_measure_code (code, description) VALUES ('80','Chemical Oxidation');
INSERT INTO control_measure_code (code, description) VALUES ('85','Wet Cyclonic Separator');
INSERT INTO control_measure_code (code, description) VALUES ('90','Conversion to Variable Vapor Space Tank');
INSERT INTO control_measure_code (code, description) VALUES ('99','Other Control Device');
INSERT INTO control_measure_code (code, description) VALUES ('5','Gravity Collector - Medium Efficiency');
INSERT INTO control_measure_code (code, description) VALUES ('12','Electrostatic Precipitator - Low Efficiency');
INSERT INTO control_measure_code (code, description) VALUES ('30','Use of  Fuel with Low Nitrogen Content');
INSERT INTO control_measure_code (code, description) VALUES ('53','Venturi Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('71','Fluid Bed Dry Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('77','Multiple Cyclone w/ Fly Ash Reinjection');
INSERT INTO control_measure_code (code, description) VALUES ('117','Packed Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('125','Low Pressure Scrubber');
INSERT INTO control_measure_code (code, description) VALUES ('152','Mist Eliminator - High Efficiency');
INSERT INTO control_measure_code (code, description) VALUES ('0','Uncontrolled');
INSERT INTO control_measure_code (code, description) VALUES ('300','Devices Repeated in Series');
INSERT INTO control_measure_code (code, description) VALUES ('301','Fuel reburning');
INSERT INTO control_measure_code (code, description) VALUES ('302','Biofilter');
INSERT INTO control_measure_code (code, description) VALUES ('303','Catalytic Additives');
INSERT INTO control_measure_code (code, description) VALUES ('304','Enclosed Combustor');
INSERT INTO control_measure_code (code, description) VALUES ('305','Diesel Particulate Filters (DPF)');
INSERT INTO control_measure_code (code, description) VALUES ('306','Duct Sorbent Injection');
INSERT INTO control_measure_code (code, description) VALUES ('307','Furnace Sorbent Injection');
INSERT INTO control_measure_code (code, description) VALUES ('308','Wet Sorbent Injection');
INSERT INTO control_measure_code (code, description) VALUES ('309','Leak Detection and Repair (LDAR) Program');
INSERT INTO control_measure_code (code, description) VALUES ('310','Non-Selective Catalytic Reduction (NSCR)');
INSERT INTO control_measure_code (code, description) VALUES ('311','Other Pollution Prevention Technique');
INSERT INTO control_measure_code (code, description) VALUES ('312','Oxidation Catalyst');
INSERT INTO control_measure_code (code, description) VALUES ('313','Spray booth and Filter');
INSERT INTO control_measure_code (code, description) VALUES ('314','Spray booth and Overspray Arrestor');
INSERT INTO control_measure_code (code, description) VALUES ('315','Spray guns - High Volume, Low Pressure (HVLP)');
INSERT INTO control_measure_code (code, description) VALUES ('316','Ultra Low NOx Burners (ULNB)');
INSERT INTO control_measure_code (code, description) VALUES ('317','Recuperative Thermal Oxidizer');
INSERT INTO control_measure_code (code, description) VALUES ('318','Product Substitution');
INSERT INTO control_measure_code (code, description) VALUES ('319','Regenerative Thermal Oxidizer');
INSERT INTO control_measure_code (code, description) VALUES ('220','CEM Upgrade and Increased Monitoring Frequency of PM Controls');
INSERT INTO control_measure_code (code, description) VALUES ('320','Combustion Device');
INSERT INTO control_measure_code (code, description) VALUES ('321','Cover Vented to Control Device');
INSERT INTO control_measure_code (code, description) VALUES ('322','External Floating Roof Tank');
INSERT INTO control_measure_code (code, description) VALUES ('323','Fixed Roof Tank');
INSERT INTO control_measure_code (code, description) VALUES ('324','Fixed Roof Tank vented to Control Device');
INSERT INTO control_measure_code (code, description) VALUES ('325','Fixed Roof Tank with Internal Floating Roof');
INSERT INTO control_measure_code (code, description) VALUES ('326','Floating Membrane Cover');
INSERT INTO control_measure_code (code, description) VALUES ('327','Floating Roof');
INSERT INTO control_measure_code (code, description) VALUES ('328','Internal Floating Roof');
INSERT INTO control_measure_code (code, description) VALUES ('329','Multiple Controls in Series');
INSERT INTO control_measure_code (code, description) VALUES ('330','Pressurized Tank');
INSERT INTO control_measure_code (code, description) VALUES ('331','Process Modification');
INSERT INTO control_measure_code (code, description) VALUES ('332','Vapor Balancing');
INSERT INTO control_measure_code (code, description) VALUES ('333','Thermal Catalytic Oxidizer without heat recovery');
INSERT INTO control_measure_code (code, description) VALUES ('334','Rotary Bed Protector');
INSERT INTO control_measure_code (code, description) VALUES ('335','Process Incineration in onsite unit (100% of exhaust gas)');
INSERT INTO control_measure_code (code, description) VALUES ('336','Process Incineration in onsite unit (<100% of exhaust gas)');
INSERT INTO control_measure_code (code, description) VALUES ('337','Thermal Catalytic Oxidizer');
COMMIT;

ALTER TABLE control ADD COLUMN control_measure_code VARCHAR(20) NOT NULL DEFAULT '0';
ALTER TABLE control ALTER COLUMN control_measure_code DROP DEFAULT;

ALTER TABLE control
    ADD CONSTRAINT control_measure_code_fkey FOREIGN KEY (control_measure_code)
    REFERENCES control_measure_code (code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

