ALTER TABLE unit_measure_code ADD COLUMN unit_type character varying(20) NOT NULL DEFAULT 'UNSUPPORTED';

ALTER TABLE unit_measure_code ADD COLUMN calculation_variable character varying(100);

update unit_measure_code set unit_type = 'ACF/TIME', calculation_variable = '1 / [min]' where code = 'ACFM';
update unit_measure_code set unit_type = 'ACF/TIME', calculation_variable = '1 / [s]' where code = 'ACFS';
update unit_measure_code set unit_type = 'BBL-TIME', calculation_variable = '1 * year' where code = 'BBL-YR';
update unit_measure_code set unit_type = 'POWER', calculation_variable = '9.8095 * [k] * w' where code = 'BLRHP';
update unit_measure_code set unit_type = 'ENERGY/VOLUME', calculation_variable = 'btu / [gall]' where code = 'BTU/GAL';
update unit_measure_code set unit_type = 'POWER', calculation_variable = 'btu / [h]' where code = 'BTU/HR';
update unit_measure_code set unit_type = 'ENERGY/MASS', calculation_variable = 'btu / sTon' where code = 'BTU/TON';
update unit_measure_code set unit_type = 'AREA', calculation_variable = '100 * [acre]' where code = 'E2ACRE';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '100 * [kg]' where code = 'E2KG';
update unit_measure_code set unit_type = 'AREA', calculation_variable = '[k] * [acre]' where code = 'E3ACRE';
update unit_measure_code set unit_type = 'BBL-TIME', calculation_variable = '[k] * 1 * year' where code = 'E3BBL-YR';
update unit_measure_code set unit_type = 'VOLUME-TIME', calculation_variable = 'year * [k] * ft3 / 12' where code = 'E3BDFT-Y';
update unit_measure_code set unit_type = 'POWER', calculation_variable = '[k] * btu / [h]' where code = 'E3BTU/HR';
update unit_measure_code set unit_type = 'CASE', calculation_variable = '[k] * 1' where code = 'E3CASE';
update unit_measure_code set unit_type = 'EACH-TIME', calculation_variable = '1000 * 1 * [h]' where code = 'E3EA-HR';
update unit_measure_code set unit_type = 'EACH-TIME', calculation_variable = '1000 * 1 * year' where code = 'E3EA-YR';
update unit_measure_code set unit_type = 'AREA-TIME', calculation_variable = '[k] * [ft] * [ft] * [h]' where code = 'E3FT2-HR';
update unit_measure_code set unit_type = 'VOLUME-TIME', calculation_variable = '[k] * [gall] * [h]' where code = 'E3GAL-HR';
update unit_measure_code set unit_type = 'VOLUME-TIME', calculation_variable = '[k] * [gall] * year' where code = 'E3GAL-YR';
update unit_measure_code set unit_type = 'AREA', calculation_variable = '[k] * [ha]' where code = 'E3HECTR';
update unit_measure_code set unit_type = 'POWER', calculation_variable = '[k] * hp' where code = 'E3HP';
update unit_measure_code set unit_type = 'TIME', calculation_variable = '[k] * [h]' where code = 'E3HR';
update unit_measure_code set unit_type = 'ENERGY', calculation_variable = '[k] * 3600 * [k] * [J]' where code = 'E3KW-HR';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '[k] * [lb] / [h]' where code = 'E3LB/HR';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[k] * [m3]' where code = 'E3M3';
update unit_measure_code set unit_type = 'SPEED', calculation_variable = '[k] * [mile] * year' where code = 'E3MI-YR';
update unit_measure_code set unit_type = 'MASS-TIME', calculation_variable = '[k] * sTon * year' where code = 'E3TON-YR';
update unit_measure_code set unit_type = 'POWER', calculation_variable = '100000 * hp' where code = 'E5HP';
update unit_measure_code set unit_type = 'BBL', calculation_variable = '[M] * 1' where code = 'E6BBL';
update unit_measure_code set unit_type = 'POWER', calculation_variable = '[M] * btu / [h]' where code = 'E6BTU/HR';
update unit_measure_code set unit_type = 'EACH-TIME', calculation_variable = '[M] * 1 * year' where code = 'E6EA-YR';
update unit_measure_code set unit_type = 'DSCF', calculation_variable = '[M] * 1' where code = 'E6FT3SD';
update unit_measure_code set unit_type = 'CHECK', calculation_variable = 'CHECK' where code = 'E6GAL-D';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[M] * [l]' where code = 'E6L';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[M] * [m3]' where code = 'E6M3';
update unit_measure_code set unit_type = 'EACH-TIME', calculation_variable = '1 / [day]' where code = 'EACH-DAY';
update unit_measure_code set unit_type = 'EACH-TIME', calculation_variable = '1 / [h]' where code = 'EACH-HR';
update unit_measure_code set unit_type = 'EACH-TIME', calculation_variable = '1 / year' where code = 'EACH-YR';
update unit_measure_code set unit_type = 'SPEED', calculation_variable = '[ft] / [min]' where code = 'FPM';
update unit_measure_code set unit_type = 'SPEED', calculation_variable = '[ft] / [s]' where code = 'FPS';
update unit_measure_code set unit_type = 'AREA-TIME', calculation_variable = '[ft] * [ft] * [h]' where code = 'FT2-HR';
update unit_measure_code set unit_type = 'AREA-TIME', calculation_variable = '[ft] * [ft] * year' where code = 'FT2-YR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[gall] / year' where code = 'GAL/YR';
update unit_measure_code set unit_type = 'VOLUME-TIME', calculation_variable = '[gall] * [h]' where code = 'GAL-HR';
update unit_measure_code set unit_type = 'AREA', calculation_variable = '[ha]' where code = 'HECTR';
update unit_measure_code set unit_type = 'AREA-TIME', calculation_variable = '[ha] * year' where code = 'HECTR-YR';
update unit_measure_code set unit_type = 'POWER', calculation_variable = 'hp' where code = 'HP';
update unit_measure_code set unit_type = 'ENERGY', calculation_variable = '[J]' where code = 'J';
update unit_measure_code set unit_type = 'MASS/AREA', calculation_variable = '[kg] / [ha]' where code = 'KG/HECTR';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[k] * [l]' where code = 'KL';
update unit_measure_code set unit_type = 'LENGTH', calculation_variable = '[km]' where code = 'KM';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '[k] * [t]' where code = 'KTONNE';
update unit_measure_code set unit_type = 'POWER', calculation_variable = '[k] * w' where code = 'KW';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[l]' where code = 'L';
update unit_measure_code set unit_type = 'LENGTH', calculation_variable = '[m]' where code = 'M';
update unit_measure_code set unit_type = 'AREA-TIME', calculation_variable = '[m2] * [h]' where code = 'M2-HR';
update unit_measure_code set unit_type = 'AREA/TIME', calculation_variable = '[m2] / [min]' where code = 'M2-MIN';
update unit_measure_code set unit_type = 'MASS-TIME', calculation_variable = '[M] * [gr] * year' where code = 'MG-YR';
update unit_measure_code set unit_type = 'AREA', calculation_variable = '[mile] * [mile]' where code = 'MILE2';
update unit_measure_code set unit_type = 'AREA-TIME', calculation_variable = '[mile] * [mile] * year' where code = 'MILE2-YR';
update unit_measure_code set unit_type = 'POWER', calculation_variable = '[M] * btu / [h]' where code = 'MMBTU/HR';
update unit_measure_code set unit_type = 'RADIOACTIVITY', calculation_variable = '[n] * 1' where code = 'NCURIE';
update unit_measure_code set unit_type = 'RADIOACTIVITY', calculation_variable = '[p] * 1' where code = 'PCURIE';
update unit_measure_code set unit_type = 'TIME', calculation_variable = '[s]' where code = 'SEC';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '[t]' where code = 'TONNE';
update unit_measure_code set unit_type = 'MASS-TIME', calculation_variable = 'sTon * year' where code = 'TON-YR';
update unit_measure_code set unit_type = 'RADIOACTIVITY', calculation_variable = '[mic] * 1' where code = 'UCURIE';
update unit_measure_code set unit_type = 'AREA/TIME', calculation_variable = '[acre] / year' where code = 'ACRE/YR';
update unit_measure_code set unit_type = 'BALE/TIME', calculation_variable = '1 / [h]' where code = 'BALE/HR';
update unit_measure_code set unit_type = 'BBL/TIME', calculation_variable = '1 / [day]' where code = 'BBL/DAY';
update unit_measure_code set unit_type = 'BBL/TIME', calculation_variable = '1 / year' where code = 'BBL/YR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = 'ft3 / 12 / [day]' where code = 'BDFT/DAY';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = 'ft3 / 12 / [h]' where code = 'BDFT/HR';
update unit_measure_code set unit_type = 'BUSHEL/TIME', calculation_variable = '1 / [h]' where code = 'BUSHEL/HR';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '100 * [lb] / [h]' where code = 'E2LB/HR';
update unit_measure_code set unit_type = 'BBL/TIME', calculation_variable = '1000 / [day]' where code = 'E3BBL/DAY';
update unit_measure_code set unit_type = 'BBL/TIME', calculation_variable = '1000 / [h]' where code = 'E3BBL/HR';
update unit_measure_code set unit_type = 'BBL/TIME', calculation_variable = '1000 / year' where code = 'E3BBL/YR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[k] * ft3 / 12 / [h]' where code = 'E3BDFT/HR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[k] * ft3 / 12 / year' where code = 'E3BDFT/YR';
update unit_measure_code set unit_type = 'AREA/TIME', calculation_variable = '[k] * [ft] * [ft] / [h]' where code = 'E3FT2/HR';
update unit_measure_code set unit_type = 'AREA/TIME', calculation_variable = '[k] * [ft] * [ft] / year' where code = 'E3FT2/YR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[k] * ft3 / [day]' where code = 'E3FT3/DAY';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[k] * ft3 / [h]' where code = 'E3FT3/HR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[k] * ft3 / [min]' where code = 'E3FT3/MIN';
update unit_measure_code set unit_type = 'SCF/TIME', calculation_variable = '1000 / [day]' where code = 'E3FT3S/DAY';
update unit_measure_code set unit_type = 'SCF/TIME', calculation_variable = '1000 / [h]' where code = 'E3FT3S/HR';
update unit_measure_code set unit_type = 'SCF/TIME', calculation_variable = '1000 / year' where code = 'E3FT3S/YR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[k] * [gall] / [day]' where code = 'E3GAL/DAY';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[k] * [gall] / [h]' where code = 'E3GAL/HR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[k] * [gall] / year' where code = 'E3GAL/MIN';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '[k] * [lb] / year' where code = 'E3LB/YR';
update unit_measure_code set unit_type = 'SPEED', calculation_variable = '[k] * [mile] / year' where code = 'E3MILE/YR';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '[k] *sTon / [day]' where code = 'E3TON/DAY';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '[k] * sTon / year' where code = 'E3TON/YR';
update unit_measure_code set unit_type = 'AREA/TIME', calculation_variable = '10000 * [ft] * [ft] / year' where code = 'E4FT2/YR';
update unit_measure_code set unit_type = 'BBL/TIME', calculation_variable = '[M] * 1 / [day]' where code = 'E6BBL/DAY';
update unit_measure_code set unit_type = 'AREA/TIME', calculation_variable = '[M] * [ft] * [ft] / [day]' where code = 'E6FT2/DAY';
update unit_measure_code set unit_type = 'AREA/TIME', calculation_variable = '[M] * [ft] * [ft] / year' where code = 'E6FT2/YR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[M] * ft3 / [day]' where code = 'E6FT3/DAY';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[M] * ft3 / [h]' where code = 'E6FT3/HR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[M] * ft3 / year' where code = 'E6FT3/YR';
update unit_measure_code set unit_type = 'SCF/TIME', calculation_variable = '[M] * 1 / [day]' where code = 'E6FT3S/DAY';
update unit_measure_code set unit_type = 'SCF/TIME', calculation_variable = '[M] * 1 / [h]' where code = 'E6FT3S/HR';
update unit_measure_code set unit_type = 'SCF/TIME', calculation_variable = '[M] * 1 / year' where code = 'E6FT3S/YR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[M] * [gall] / [day]' where code = 'E6GAL/DAY';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[M] * [gall] / year' where code = 'E6GAL/YR';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '[M] * [lb] / [day]' where code = 'E6LB/DAY';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '[M] * [lb] / [h]' where code = 'E6LB/HR';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '[M] * [lb] / year' where code = 'E6LB/YR';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '[M] * sTon / year' where code = 'E6TON/YR';
update unit_measure_code set unit_type = 'SPEED', calculation_variable = '[ft] / [h]' where code = 'FT/HR';
update unit_measure_code set unit_type = 'SPEED', calculation_variable = '[ft] / [min]' where code = 'FT/MIN';
update unit_measure_code set unit_type = 'AREA/TIME', calculation_variable = '[ft] * [ft] / [h]' where code = 'FT2/HR';
update unit_measure_code set unit_type = 'AREA/TIME', calculation_variable = '[ft] * [ft] / [min]' where code = 'FT2/MIN';
update unit_measure_code set unit_type = 'AREA/TIME', calculation_variable = '[ft] * [ft] / year' where code = 'FT2/YR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = 'ft3 / [day]' where code = 'FT3/DAY';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = 'ft3 / [h]' where code = 'FT3/HR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = 'ft3 / [min]' where code = 'FT3/MIN';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = 'ft3 / year' where code = 'FT3/YR';
update unit_measure_code set unit_type = 'SCF/TIME', calculation_variable = '1 / [h]' where code = 'FT3S/HR';
update unit_measure_code set unit_type = 'SCF/TIME', calculation_variable = '1 / [min]' where code = 'FT3S/MIN';
update unit_measure_code set unit_type = 'SCF/TIME', calculation_variable = '1 / year' where code = 'FT3S/YR';
update unit_measure_code set unit_type = 'DSCF/TIME', calculation_variable = '1 / [h]' where code = 'FT3SD/HR';
update unit_measure_code set unit_type = 'DSCF/TIME', calculation_variable = '1 / [min]' where code = 'FT3SD/MIN';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[gall] / [day]' where code = 'GAL/DAY';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[gall] / [h]' where code = 'GAL/HR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[gall] / [min]' where code = 'GAL/MIN';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[l] / [day]' where code = 'L/DAY';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '[lb] / [day]' where code = 'LB/DAY';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '[lb] / [h]' where code = 'LB/HR';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '[lb] / [min]' where code = 'LB/MIN';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '[lb] / [s]' where code = 'LB/SEC';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '[lb] / year' where code = 'LB/YR';
update unit_measure_code set unit_type = 'SPEED', calculation_variable = '[mile] / year' where code = 'MILE/YR';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = 'sTon / [day]' where code = 'TON/DAY';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = 'sTon / [h]' where code = 'TON/HR';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = 'sTon / year' where code = 'TON/YR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '27 * ft3 / [h]' where code = 'YD3/HR';
update unit_measure_code set unit_type = 'POWER', calculation_variable = '[G] * w' where code = 'GW';
update unit_measure_code set unit_type = 'AREA-TIME', calculation_variable = '[ha] * [h]' where code = 'HECTR-HR';
update unit_measure_code set unit_type = 'AREA', calculation_variable = '[km2]' where code = 'KM2';
update unit_measure_code set unit_type = 'AREA', calculation_variable = '[m2]' where code = 'M2';
update unit_measure_code set unit_type = 'TIME', calculation_variable = '[min]' where code = 'MIN';
update unit_measure_code set unit_type = 'POWER', calculation_variable = '[M] * w' where code = 'MW';
update unit_measure_code set unit_type = 'MASS/AREA', calculation_variable = 'sTon / [acre]' where code = 'TON/ACRE';
update unit_measure_code set unit_type = 'TIME', calculation_variable = 'year' where code = 'YR';
update unit_measure_code set unit_type = 'POWER', calculation_variable = '[M] * btu / year' where code = 'E6BTU/YR';
update unit_measure_code set unit_type = 'BBL/TIME', calculation_variable = '1 / [h]' where code = 'BBL/HR';
update unit_measure_code set unit_type = 'MASS/TIME', calculation_variable = '100 * [lb] / [day]' where code = 'E2LB/DAY';
update unit_measure_code set unit_type = 'SPEED', calculation_variable = '[k] * [ft] / year' where code = 'E3FT/YR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[k] * ft3 / year' where code = 'E3FT3/YR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[k] * [gall] / year' where code = 'E3GAL/YR';
update unit_measure_code set unit_type = 'VOLUME/TIME', calculation_variable = '[M] * ft3 / 12 / year' where code = 'E6BDFT/YR';
update unit_measure_code set unit_type = 'SCF', calculation_variable = '1' where code = 'SCF';
update unit_measure_code set unit_type = 'RADIOACTIVITY', calculation_variable = '1' where code = 'CURIE';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '[gr]' where code = 'G';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '[mg]' where code = 'MILLIGRM';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '[n] * [gr]' where code = 'NG';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '[mic] * [gr]' where code = 'UG';
update unit_measure_code set unit_type = 'AREA', calculation_variable = '[acre]' where code = 'ACRE';
update unit_measure_code set unit_type = 'AREA-TIME', calculation_variable = '[acre] * [day]' where code = 'ACRE-DAY';
update unit_measure_code set unit_type = 'AREA-TIME', calculation_variable = '[acre] * year / 12' where code = 'ACRE-MONTH';
update unit_measure_code set unit_type = 'AREA-TIME', calculation_variable = '[acre] * year' where code = 'ACRE-YR';
update unit_measure_code set unit_type = 'BALE', calculation_variable = '1' where code = 'BALE';
update unit_measure_code set unit_type = 'BBL', calculation_variable = '1' where code = 'BBL';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = 'ft3 / 12' where code = 'BDFT';
update unit_measure_code set unit_type = 'ENERGY', calculation_variable = 'btu' where code = 'BTU';
update unit_measure_code set unit_type = 'BUSHEL', calculation_variable = '1' where code = 'BUSHEL';
update unit_measure_code set unit_type = 'TIME', calculation_variable = '[day]' where code = 'DAY';
update unit_measure_code set unit_type = 'BBL', calculation_variable = '100' where code = 'E2BBL';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '100 * [lb]' where code = 'E2LB';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '100 * sTon' where code = 'E2TON';
update unit_measure_code set unit_type = 'BBL', calculation_variable = '1000' where code = 'E3BBL';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[k] * ft3 / 12' where code = 'E3BDFT';
update unit_measure_code set unit_type = 'ENERGY', calculation_variable = '[k] * btu' where code = 'E3BTU';
update unit_measure_code set unit_type = 'BUSHEL', calculation_variable = '1000' where code = 'E3BU';
update unit_measure_code set unit_type = 'EACH', calculation_variable = '1000' where code = 'E3EACH';
update unit_measure_code set unit_type = 'LENGTH', calculation_variable = '[k] * [ft]' where code = 'E3FT';
update unit_measure_code set unit_type = 'AREA', calculation_variable = '[k] * [ft] * [ft]' where code = 'E3FT2';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[k] * ft3' where code = 'E3FT3';
update unit_measure_code set unit_type = 'SCF', calculation_variable = '1000' where code = 'E3FT3S';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[k] * [gall]' where code = 'E3GAL';
update unit_measure_code set unit_type = 'ENERGY', calculation_variable = '[k] * hp * [h]' where code = 'E3HP-HR';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '[k] * [lb]' where code = 'E3LB';
update unit_measure_code set unit_type = 'LENGTH', calculation_variable = '[k] * [mile]' where code = 'E3MILE';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '[k] * sTon' where code = 'E3TON';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[k] * 27 * ft3' where code = 'E3YD3';
update unit_measure_code set unit_type = 'AREA', calculation_variable = '10000 * [ft] * [ft]' where code = 'E4FT2';
update unit_measure_code set unit_type = 'ENERGY', calculation_variable = '100000 * hp * [h]' where code = 'E5HP-HR';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[M] * ft3 / 12' where code = 'E6BDFT';
update unit_measure_code set unit_type = 'ENERGY', calculation_variable = '[M] * btu' where code = 'E6BTU';
update unit_measure_code set unit_type = 'EACH', calculation_variable = '[M] * 1' where code = 'E6EACH';
update unit_measure_code set unit_type = 'AREA', calculation_variable = '[M] * [ft] * [ft]' where code = 'E6FT2';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[M] * ft3' where code = 'E6FT3';
update unit_measure_code set unit_type = 'SCF', calculation_variable = '[M] * 1' where code = 'E6FT3S';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[M] * [gall]' where code = 'E6GAL';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '[M] * [lb]' where code = 'E6LB';
update unit_measure_code set unit_type = 'LENGTH', calculation_variable = '[M] * [mile]' where code = 'E6MILE';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '[M] * sTon' where code = 'E6TON';
update unit_measure_code set unit_type = 'EACH', calculation_variable = '1' where code = 'EACH';
update unit_measure_code set unit_type = 'LENGTH', calculation_variable = '[ft]' where code = 'FT';
update unit_measure_code set unit_type = 'AREA', calculation_variable = '[ft] * [ft]' where code = 'FT2';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = 'ft3' where code = 'FT3';
update unit_measure_code set unit_type = 'SCF', calculation_variable = '1' where code = 'FT3S';
update unit_measure_code set unit_type = 'SCF', calculation_variable = '1 / [min] * year' where code = 'FT3S/M-Y';
update unit_measure_code set unit_type = 'DSCF', calculation_variable = '1' where code = 'FT3SD';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[gall]' where code = 'GAL';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[gall] * [min] / year' where code = 'GPM-YR';
update unit_measure_code set unit_type = 'ENERGY', calculation_variable = 'hp * [h]' where code = 'HP-HR';
update unit_measure_code set unit_type = 'TIME', calculation_variable = '[h]' where code = 'HR';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '[kg]' where code = 'KG';
update unit_measure_code set unit_type = 'ENERGY', calculation_variable = '3600 * [k] * [J]' where code = 'KW-HR';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '[lb]' where code = 'LB';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '[m3]' where code = 'M3';
update unit_measure_code set unit_type = 'MASS', calculation_variable = '[M] * [gr]' where code = 'MEGAGRAM';
update unit_measure_code set unit_type = 'LENGTH', calculation_variable = '[mile]' where code = 'MILE';
update unit_measure_code set unit_type = 'ENERGY', calculation_variable = '[M] * btu' where code = 'MMBTU';
update unit_measure_code set unit_type = 'ENERGY', calculation_variable = '3600 * [M] * [J]' where code = 'MW-HR';
update unit_measure_code set unit_type = 'ENERGY', calculation_variable = '100000 * btu' where code = 'THERM';
update unit_measure_code set unit_type = 'MASS', calculation_variable = 'sTon' where code = 'TON';
update unit_measure_code set unit_type = 'MASS-LENGTH', calculation_variable = 'sTon * [mile]' where code = 'TON-MILE';
update unit_measure_code set unit_type = 'AREA', calculation_variable = '9 * [ft] * [ft]' where code = 'YD2';
update unit_measure_code set unit_type = 'VOLUME', calculation_variable = '27 * ft3' where code = 'YD3';

