-- Control Measure
INSERT INTO control_measure_code (code, description) VALUES ('338', 'Turbine to Burn Waste Gas');
INSERT INTO control_measure_code (code, description) VALUES ('339', 'Boiler to Burn Waste Gas');
INSERT INTO control_measure_code (code, description) VALUES ('340', 'Internal Combustion Device to Burn Waste Gas');

-- Facility Source Type
UPDATE facility_source_type_code SET description = 'Tire Manuf (not retread)' WHERE code = '186';

-- NAICS
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (51781, 'All Other Telecommunications', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (5192, 'Web Search Portals, Libraries, Archives, and Other Information Services', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (51921, 'Libraries and Archives', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (51929, 'Web Search Portals and All Other Information Services', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (52218, 'Savings Institutions and Other Depository Credit Intermediation', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (52315, 'Investment Banking and Securities Intermediation', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (52316, 'Commodity Contracts Intermediation', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (52394, 'Portfolio Management and Investment Advice', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (4581, 'Clothing and Clothing Accessories Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45811, 'Clothing and Clothing Accessories Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (4582, 'Shoe Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45821, 'Shoe Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (4583, 'Jewelry, Luggage, and Leather Goods Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45831, 'Jewelry Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45832, 'Luggage and Leather Goods Retailers', 2023);
INSERT INTO naics_code (code, description, last_inventory_year) VALUES (459, 'Sporting Goods, Hobby, Musical Instrument, Book, and Miscellaneous Retailers', 2002);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (4591, 'Sporting Goods, Hobby, and Musical Instrument Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45911, 'Sporting Goods Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45912, 'Hobby, Toy, and Game Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45913, 'Sewing, Needlework, and Piece Goods Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45914, 'Musical Instrument and Supplies Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (4592, 'Book Retailers and News Dealers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45921, 'Book Retailers and News Dealers', 2023);
INSERT INTO naics_code (code, description, last_inventory_year, map_to) VALUES (4593, 'Florists', 2021, '459310');
INSERT INTO naics_code (code, description, last_inventory_year, map_to) VALUES (45931, 'Florists', 2021, '459310');
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (4594, 'Office Supplies, Stationery, and Gift Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45941, 'Office Supplies and Stationery Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45942, 'Gift, Novelty, and Souvenir Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (4595, 'Used Merchandise Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45951, 'Used Merchandise Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (4599, 'Other Miscellaneous Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45991, 'Pet and Pet Supplies Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45992, 'Art Dealers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45993, 'Manufactured (Mobile) Home Dealers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45999, 'All Other Miscellaneous Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (4492, 'Electronics and Appliance Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (44921, 'Electronics and Appliance Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (5178, 'All Other Telecommunications', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (44133, 'Automotive Parts and Accessories Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (44134, 'Tire Dealers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (44414, 'Hardware Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (44418, 'Other Building Material Dealers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (44423, 'Outdoor Power Equipment Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (44424, 'Nursery, Garden Center, and Farm Supply Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (44513, 'Convenience Retailers and Vending Machine Operators', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (44524, 'Meat Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (44525, 'Fish and Seafood Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (44532, 'Beer, Wine, and Liquor Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (449, 'Furniture, Home Furnishings, Electronics, and Appliance Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (4491, 'Furniture and Home Furnishings Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (44911, 'Furniture Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (44912, 'Home Furnishings Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (31512, 'Apparel Knitting Mills', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (31525, 'Cut and Sew Apparel Manufacturing (except Contractors)', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (455, 'General Merchandise Retailers', 2023);
INSERT INTO naics_code (code, description, last_inventory_year, map_to) VALUES (4551, 'Department Stores', 2021, '455110');
INSERT INTO naics_code (code, description, last_inventory_year, map_to) VALUES (45511, 'Department Stores', 2021, '455110');
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (4552, 'Warehouse Clubs, Supercenters, and Other General Merchandise Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45521, 'Warehouse Clubs, Supercenters, and Other General Merchandise Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (456, 'Health and Personal Care Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (4561, 'Health and Personal Care Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45611, 'Pharmacies and Drug Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45612, 'Cosmetics, Beauty Supplies, and Perfume Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45613, 'Optical Goods Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (45619, 'Other Health and Personal Care Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (457, 'Gasoline Stations and Fuel Dealers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (4571, 'Gasoline Stations', 2023);
INSERT INTO naics_code (code, description, last_inventory_year, map_to) VALUES (45711, 'Gasoline Stations with Convenience Stores', 2021, '457110');
INSERT INTO naics_code (code, description, last_inventory_year, map_to) VALUES (45712, 'Other Gasoline Stations', 2021, '457120');
INSERT INTO naics_code (code, description, last_inventory_year, map_to) VALUES (4572, 'Fuel Dealers', 2021, '457210');
INSERT INTO naics_code (code, description, last_inventory_year, map_to) VALUES (45721, 'Fuel Dealers', 2021, '457210');
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (458, 'Clothing, Clothing Accessories, Shoe, and Jewelry Retailers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (33513, 'Electric Lighting Equipment Manufacturing', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (42435, 'Clothing and Clothing Accessories Merchant Wholesalers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (513, 'Publishing Industries', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (5131, 'Newspaper, Periodical, Book, and Directory Publishers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (51311, 'Newspaper Publishers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (51312, 'Periodical Publishers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (51313, 'Book Publishers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (51314, 'Directory and Mailing List Publishers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (51319, 'Other Publishers', 2023);
INSERT INTO naics_code (code, description, last_inventory_year, map_to) VALUES (5132, 'Software Publishers', 2021, '513210');
INSERT INTO naics_code (code, description, last_inventory_year, map_to) VALUES (51321, 'Software Publishers', 2021, '513210');
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (516, 'Broadcasting and Content Providers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (5161, 'Radio and Television Broadcasting Stations', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (51611, 'Radio Broadcasting Stations', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (51612, 'Television Broadcasting Stations', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (5162, 'Media Streaming Distribution Services, Social Networks, and Other Media Networks and Content Providers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (51621, 'Media Streaming Distribution Services, Social Networks, and Other Media Networks and Content Providers', 2023);
INSERT INTO naics_code (code, description, first_inventory_year) VALUES (51712, 'Telecommunications Resellers and Agents for Wireless Telecommunication Services', 2023);
UPDATE naics_code SET description = 'Electric Lamp Bulb and Part Manufacturing', last_inventory_year = 2021, map_to = '335139' WHERE code = 33511;
UPDATE naics_code SET description = 'Electric Lamp Bulb and Part Manufacturing', last_inventory_year = 2021, map_to = '335139' WHERE code = 335110;
UPDATE naics_code SET description = 'Software Publishers', last_inventory_year = 2021, map_to = '513210' WHERE code = 51121;
UPDATE naics_code SET description = 'Software Publishers', last_inventory_year = 2021, map_to = '513210' WHERE code = 511210;
UPDATE naics_code SET description = 'Radio Stations', last_inventory_year = 2021, map_to = '516110' WHERE code = 515112;
UPDATE naics_code SET description = 'Television Broadcasting', last_inventory_year = 2021, map_to = '516120' WHERE code = 51512;
UPDATE naics_code SET description = 'Television Broadcasting', last_inventory_year = 2021, map_to = '516120' WHERE code = 515120;
UPDATE naics_code SET description = 'Cable and Other Subscription Programming', last_inventory_year = 2021, map_to = '516210' WHERE code = 5152;
UPDATE naics_code SET description = 'Cable and Other Subscription Programming', last_inventory_year = 2021, map_to = '516210' WHERE code = 51521;
UPDATE naics_code SET description = 'Cable and Other Subscription Programming', last_inventory_year = 2021, map_to = '516210' WHERE code = 515210;
UPDATE naics_code SET description = 'Other Telecommunications', last_inventory_year = 2021, map_to = '517810' WHERE code = 5179;
UPDATE naics_code SET description = 'Other Telecommunications', last_inventory_year = 2021, map_to = '517810' WHERE code = 51791;
UPDATE naics_code SET description = 'Business to Business Electronic Markets', last_inventory_year = 2021, map_to = '425120' WHERE code = 42511;
UPDATE naics_code SET description = 'Business to Business Electronic Markets', last_inventory_year = 2021, map_to = '425120' WHERE code = 425110;
UPDATE naics_code SET description = 'Tobacco Product and Electronic Cigarette Merchant Wholesalers' WHERE code = 42494;
UPDATE naics_code SET description = 'Tobacco Product and Electronic Cigarette Merchant Wholesalers' WHERE code = 424940;
UPDATE naics_code SET description = 'Metal Household Furniture Manufacturing', last_inventory_year = 2021, map_to = '337126' WHERE code = 337124;
UPDATE naics_code SET description = 'Commercial, Industrial, and Institutional Electric Lighting Fixture Manufacturing', last_inventory_year = 2021, map_to = '335132' WHERE code = 335122;
UPDATE naics_code SET description = 'Bituminous Coal and Lignite Surface Mining', last_inventory_year = 2021, map_to = '212114' WHERE code = 212111;
UPDATE naics_code SET description = 'Uranium-Radium-Vanadium Ore Mining', last_inventory_year = 2021, map_to = '212290' WHERE code = 212291;
UPDATE naics_code SET description = 'Clay and Ceramic and Refractory Minerals Mining', last_inventory_year = 2021, map_to = '212323' WHERE code = 212325;
UPDATE naics_code SET description = 'Musical Instrument and Supplies Stores', last_inventory_year = 2021, map_to = '459140' WHERE code = 45114;
UPDATE naics_code SET description = 'Musical Instrument and Supplies Stores', last_inventory_year = 2021, map_to = '459140' WHERE code = 451140;
UPDATE naics_code SET description = 'Florists', last_inventory_year = 2021, map_to = '459310' WHERE code = 4531;
UPDATE naics_code SET description = 'Florists', last_inventory_year = 2021, map_to = '459310' WHERE code = 45311;
UPDATE naics_code SET description = 'Florists', last_inventory_year = 2021, map_to = '459310' WHERE code = 453110;
UPDATE naics_code SET description = 'Office Supplies and Stationery Stores', last_inventory_year = 2021, map_to = '459410' WHERE code = 453210;
UPDATE naics_code SET description = 'Other Miscellaneous Store Retailers', last_inventory_year = 2021 WHERE code = 4539;
UPDATE naics_code SET description = 'Pet and Pet Supplies Stores', last_inventory_year = 2021, map_to = '459910' WHERE code = 453910;
UPDATE naics_code SET description = 'Art Dealers', last_inventory_year = 2021, map_to = '459920' WHERE code = 45392;
UPDATE naics_code SET description = 'Art Dealers', last_inventory_year = 2021, map_to = '459920' WHERE code = 453920;
UPDATE naics_code SET description = 'Electronic Shopping and Mail-Order Houses', last_inventory_year = 2021 WHERE code = 4541;
UPDATE naics_code SET description = 'Electronic Shopping and Mail-Order Houses', last_inventory_year = 2021 WHERE code = 45411;
UPDATE naics_code SET description = 'Vending Machine Operators', last_inventory_year = 2021, map_to = '445132' WHERE code = 4542;
UPDATE naics_code SET description = 'Vending Machine Operators', last_inventory_year = 2021, map_to = '445132' WHERE code = 45421;
UPDATE naics_code SET description = 'Vending Machine Operators', last_inventory_year = 2021, map_to = '445132' WHERE code = 454210;
UPDATE naics_code SET description = 'Other Direct Selling Establishments', last_inventory_year = 2021 WHERE code = 45439;
UPDATE naics_code SET description = 'Other Direct Selling Establishments', last_inventory_year = 2021 WHERE code = 454390;
UPDATE naics_code SET description = 'Taxi and Ridesharing Services' WHERE code = 485310;
UPDATE naics_code SET description = 'Child Care Services' WHERE code = 6244;
UPDATE naics_code SET description = 'Blank Magnetic and Optical Recording Media Manufacturing', last_inventory_year = 2021, map_to = '334610' WHERE code = 334613;
UPDATE naics_code SET description = 'Lighting Fixture Manufacturing', last_inventory_year = 2021 WHERE code = 33512;
UPDATE naics_code SET description = 'Residential Electric Lighting Fixture Manufacturing', last_inventory_year = 2021, map_to = '335131' WHERE code = 335121;
UPDATE naics_code SET description = 'Sporting Goods, Hobby, and Musical Instrument Stores', last_inventory_year = 2021 WHERE code = 4511;
UPDATE naics_code SET description = 'Sporting Goods Stores', last_inventory_year = 2021, map_to = '459110' WHERE code = 45111;
UPDATE naics_code SET description = 'Sporting Goods Stores', last_inventory_year = 2021, map_to = '459110' WHERE code = 451110;
UPDATE naics_code SET description = 'Hobby, Toy, and Game Stores', last_inventory_year = 2021, map_to = '459120' WHERE code = 45112;
UPDATE naics_code SET description = 'Hobby, Toy, and Game Stores', last_inventory_year = 2021, map_to = '459120' WHERE code = 451120;
UPDATE naics_code SET description = 'Book Stores and News Dealers', last_inventory_year = 2021 WHERE code = 4512;
UPDATE naics_code SET description = 'Book Stores and News Dealers', last_inventory_year = 2021 WHERE code = 45121;
UPDATE naics_code SET description = 'Book Stores', last_inventory_year = 2021, map_to = '459210' WHERE code = 451211;
UPDATE naics_code SET description = 'News Dealers and Newsstands', last_inventory_year = 2021, map_to = '459210' WHERE code = 451212;
UPDATE naics_code SET description = 'Office Supplies, Stationery, and Gift Stores', last_inventory_year = 2021 WHERE code = 4532;
UPDATE naics_code SET description = 'Used Merchandise Stores', last_inventory_year = 2021, map_to = '459510' WHERE code = 45331;
UPDATE naics_code SET description = 'Pet and Pet Supplies Stores', last_inventory_year = 2021, map_to = '459910' WHERE code = 45391;
UPDATE naics_code SET description = 'All Other Miscellaneous Store Retailers', last_inventory_year = 2021 WHERE code = 45399;
UPDATE naics_code SET description = 'Tobacco Stores', last_inventory_year = 2021, map_to = '459991' WHERE code = 453991;
UPDATE naics_code SET description = 'All Other Miscellaneous Store Retailers (except Tobacco Stores)', last_inventory_year = 2021, map_to = '455219' WHERE code = 453998;
UPDATE naics_code SET description = 'Direct Selling Establishments', last_inventory_year = 2021 WHERE code = 4543;
UPDATE naics_code SET description = 'Fuel Dealers', last_inventory_year = 2021, map_to = '457210' WHERE code = 45431;
UPDATE naics_code SET description = 'Tobacco Manufacturing', last_inventory_year = 2021, map_to = '312230' WHERE code = 3122;
UPDATE naics_code SET description = 'Fertilizer and Compost Manufacturing' WHERE code = 32531;
UPDATE naics_code SET description = 'Photographic Film, Paper, Plate, Chemical, and Copy Toner Manufacturing' WHERE code = 325992;
UPDATE naics_code SET description = 'Directory and Mailing List Publishers', last_inventory_year = 2021, map_to = '513140' WHERE code = 511140;
UPDATE naics_code SET description = 'Child Care Services' WHERE code = 62441;
UPDATE naics_code SET description = 'Child Care Services' WHERE code = 624410;
UPDATE naics_code SET description = 'Hosiery and Sock Mills', last_inventory_year = 2021, map_to = '315120' WHERE code = 31511;
UPDATE naics_code SET description = 'Men''s and Boys'' Cut and Sew Apparel Manufacturing', last_inventory_year = 2021, map_to = '315250' WHERE code = 31522;
UPDATE naics_code SET description = 'Scale and Balance Manufacturing', last_inventory_year = 2021, map_to = '333998' WHERE code = 333997;
UPDATE naics_code SET description = 'All Other Miscellaneous General Purpose Machinery Manufacturing', last_inventory_year = 2021, map_to = '333998' WHERE code = 333999;
UPDATE naics_code SET description = 'Newsprint Mills', last_inventory_year = 2021, map_to = '322120' WHERE code = 322122;
UPDATE naics_code SET description = 'Paper (except Newsprint) Mills', last_inventory_year = 2021, map_to = '322120' WHERE code = 322121;
UPDATE naics_code SET description = 'Indoor and Outdoor Display Advertising' WHERE code = 54185;
UPDATE naics_code SET description = 'Indoor and Outdoor Display Advertising' WHERE code = 541850;
UPDATE naics_code SET description = 'Department Stores', last_inventory_year = 2021, map_to = '455110' WHERE code = 452210;
UPDATE naics_code SET description = 'Warehouse Clubs and Supercenters', last_inventory_year = 2021, map_to = '455211' WHERE code = 452311;
UPDATE naics_code SET description = 'Software and Other Prerecorded Compact Disc, Tape, and Record Reproducing', last_inventory_year = 2021, map_to = '334610' WHERE code = 334614;
UPDATE naics_code SET description = 'Motorcycle, ATV, and All Other Motor Vehicle Dealers', last_inventory_year = 2021, map_to = '441227' WHERE code = 441228;
UPDATE naics_code SET description = 'Electronics and Appliance Stores', last_inventory_year = 2021, map_to = '449210' WHERE code = 44314;
UPDATE naics_code SET description = 'Household Appliance Stores', last_inventory_year = 2021, map_to = '449210' WHERE code = 443141;
UPDATE naics_code SET description = 'Electronics Stores', last_inventory_year = 2021, map_to = '449210' WHERE code = 443142;
UPDATE naics_code SET description = 'Fuel Dealers', last_inventory_year = 2021, map_to = '457210' WHERE code = 454310;
UPDATE naics_code SET description = 'Printing Machinery and Equipment Manufacturing', last_inventory_year = 2021, map_to = '333248' WHERE code = 333244;
UPDATE naics_code SET description = 'Other Industrial Machinery Manufacturing', last_inventory_year = 2021, map_to = '333248' WHERE code = 333249;
UPDATE naics_code SET description = 'Photographic and Photocopying Equipment Manufacturing', last_inventory_year = 2021, map_to = '333310' WHERE code = 333316;
UPDATE naics_code SET description = 'Other Commercial and Service Industry Machinery Manufacturing', last_inventory_year = 2021, map_to = '333310' WHERE code = 333318;
UPDATE naics_code SET description = 'Wholesale Trade Agents and Brokers', last_inventory_year = 2021, map_to = '425120' WHERE code = 4251;
UPDATE naics_code SET description = 'Automotive Parts, Accessories, and Tire Retailers' WHERE code = 4413;
UPDATE naics_code SET description = 'Automotive Parts and Accessories Stores', last_inventory_year = 2021, map_to = '441330' WHERE code = 441310;
UPDATE naics_code SET description = 'Tire Dealers', last_inventory_year = 2021, map_to = '441340' WHERE code = 44132;
UPDATE naics_code SET description = 'Tire Dealers', last_inventory_year = 2021, map_to = '441340' WHERE code = 441320;
UPDATE naics_code SET description = 'Furniture Stores', last_inventory_year = 2021, map_to = '449110' WHERE code = 4421;
UPDATE naics_code SET description = 'Furniture Stores', last_inventory_year = 2021, map_to = '449110' WHERE code = 44211;
UPDATE naics_code SET description = 'Home Furnishings Stores', last_inventory_year = 2021 WHERE code = 4422;
UPDATE naics_code SET description = 'Floor Covering Stores', last_inventory_year = 2021, map_to = '449121' WHERE code = 442210;
UPDATE naics_code SET description = 'Other Home Furnishings Stores', last_inventory_year = 2021 WHERE code = 44229;
UPDATE naics_code SET description = 'Electronics and Appliance Stores', last_inventory_year = 2021 WHERE code = 4431;
UPDATE naics_code SET description = 'Investigation and Personal Background Check Services' WHERE code = 561611;
UPDATE naics_code SET description = 'Hardware Stores', last_inventory_year = 2021, map_to = '444140' WHERE code = 444130;
UPDATE naics_code SET description = 'Other Building Material Dealers', last_inventory_year = 2021, map_to = '444180' WHERE code = 44419;
UPDATE naics_code SET description = 'Other Building Material Dealers', last_inventory_year = 2021, map_to = '444180' WHERE code = 444190;
UPDATE naics_code SET description = 'Outdoor Power Equipment Stores', last_inventory_year = 2021, map_to = '444230' WHERE code = 44421;
UPDATE naics_code SET description = 'Outdoor Power Equipment Stores', last_inventory_year = 2021, map_to = '444230' WHERE code = 444210;
UPDATE naics_code SET description = 'Nursery, Garden Center, and Farm Supply Stores', last_inventory_year = 2021, map_to = '444240' WHERE code = 444220;
UPDATE naics_code SET description = 'Convenience Stores', last_inventory_year = 2021, map_to = '445131' WHERE code = 445120;
UPDATE naics_code SET description = 'Meat Markets', last_inventory_year = 2021, map_to = '445240' WHERE code = 445210;
UPDATE naics_code SET description = 'Fruit and Vegetable Retailers' WHERE code = 44523;
UPDATE naics_code SET description = 'Other Specialty Food Retailers' WHERE code = 44529;
UPDATE naics_code SET description = 'Beer, Wine, and Liquor Retailers', last_inventory_year = 2021, map_to = '445320' WHERE code = 4453;
UPDATE naics_code SET description = 'Health and Personal Care Stores', last_inventory_year = 2021 WHERE code = 4461;
UPDATE naics_code SET description = 'Pharmacies and Drug Stores', last_inventory_year = 2021, map_to = '456110' WHERE code = 446110;
UPDATE naics_code SET description = 'Optical Goods Stores', last_inventory_year = 2021, map_to = '456130' WHERE code = 446130;
UPDATE naics_code SET description = 'All Other Health and Personal Care Stores', last_inventory_year = 2021, map_to = '456199' WHERE code = 446199;
UPDATE naics_code SET description = 'Other Gasoline Stations', last_inventory_year = 2021, map_to = '457120' WHERE code = 44719;
UPDATE naics_code SET description = 'Clothing Stores', last_inventory_year = 2021 WHERE code = 4481;
UPDATE naics_code SET description = 'Men''s Clothing Stores', last_inventory_year = 2021, map_to = '458110' WHERE code = 44811;
UPDATE naics_code SET description = 'Men''s Clothing Stores', last_inventory_year = 2021, map_to = '458110' WHERE code = 448110;
UPDATE naics_code SET description = 'Women''s Clothing Stores', last_inventory_year = 2021, map_to = '458110' WHERE code = 448120;
UPDATE naics_code SET description = 'Family Clothing Stores', last_inventory_year = 2021, map_to = '458110' WHERE code = 44814;
UPDATE naics_code SET description = 'Family Clothing Stores', last_inventory_year = 2021, map_to = '458110' WHERE code = 448140;
UPDATE naics_code SET description = 'Clothing Accessories Stores', last_inventory_year = 2021, map_to = '458110' WHERE code = 44815;
UPDATE naics_code SET description = 'Clothing Accessories Stores', last_inventory_year = 2021, map_to = '458110' WHERE code = 448150;
UPDATE naics_code SET description = 'Other Clothing Stores', last_inventory_year = 2021, map_to = '458110' WHERE code = 448190;
UPDATE naics_code SET description = 'Shoe Stores', last_inventory_year = 2021, map_to = '458210' WHERE code = 4482;
UPDATE naics_code SET description = 'Shoe Stores', last_inventory_year = 2021, map_to = '458210' WHERE code = 44821;
UPDATE naics_code SET description = 'Jewelry, Luggage, and Leather Goods Stores', last_inventory_year = 2021, map_to = '4583' WHERE code = 4483;
UPDATE naics_code SET description = 'Luggage and Leather Goods Stores', last_inventory_year = 2021, map_to = '458320' WHERE code = 44832;
UPDATE naics_code SET description = 'Luggage and Leather Goods Stores', last_inventory_year = 2021, map_to = '458320' WHERE code = 448320;
UPDATE naics_code SET description = 'Wholesale Trade Agents and Brokers', last_inventory_year = 2021, map_to = '425120' WHERE code = 42512;
UPDATE naics_code SET description = 'Automotive Parts and Accessories Stores', last_inventory_year = 2021, map_to = '441330' WHERE code = 44131;
UPDATE naics_code SET description = 'Furniture Stores', last_inventory_year = 2021, map_to = '449110' WHERE code = 442110;
UPDATE naics_code SET description = 'Floor Covering Stores', last_inventory_year = 2021, map_to = '449121' WHERE code = 44221;
UPDATE naics_code SET description = 'Window Treatment Stores', last_inventory_year = 2021, map_to = '449122' WHERE code = 442291;
UPDATE naics_code SET description = 'All Other Home Furnishings Stores', last_inventory_year = 2021, map_to = '449129' WHERE code = 442299;
UPDATE naics_code SET description = 'Lawn and Garden Equipment and Supplies Retailers' WHERE code = 4442;
UPDATE naics_code SET description = 'Grocery and Convenience Retailers' WHERE code = 4451;
UPDATE naics_code SET description = 'Convenience Stores', last_inventory_year = 2021, map_to = '445131' WHERE code = 44512;
UPDATE naics_code SET description = 'Specialty Food Retailers' WHERE code = 4452;
UPDATE naics_code SET description = 'Fruit and Vegetable Retailers' WHERE code = 445230;
UPDATE naics_code SET description = 'Baked Goods Retailers' WHERE code = 445291;
UPDATE naics_code SET description = 'Confectionery and Nut Retailers' WHERE code = 445292;
UPDATE naics_code SET description = 'All Other Specialty Food Stores', last_inventory_year = 2021, map_to = '445298' WHERE code = 445299;
UPDATE naics_code SET description = 'Optical Goods Stores', last_inventory_year = 2021, map_to = '456130' WHERE code = 44613;
UPDATE naics_code SET description = 'Other Health and Personal Care Stores', last_inventory_year = 2021 WHERE code = 44619;
UPDATE naics_code SET description = 'Food (Health) Supplement Stores', last_inventory_year = 2021, map_to = '456191' WHERE code = 446191;
UPDATE naics_code SET description = 'Gasoline Stations', last_inventory_year = 2021, map_to = '4571' WHERE code = 4471;
UPDATE naics_code SET description = 'Other Gasoline Stations', last_inventory_year = 2021, map_to = '457120' WHERE code = 447190;
UPDATE naics_code SET description = 'Women''s Clothing Stores', last_inventory_year = 2021, map_to = '458110' WHERE code = 44812;
UPDATE naics_code SET description = 'Other Clothing Stores', last_inventory_year = 2021, map_to = '458110' WHERE code = 44819;
UPDATE naics_code SET description = 'Shoe Stores', last_inventory_year = 2021, map_to = '458210' WHERE code = 448210;
UPDATE naics_code SET description = 'Jewelry Stores', last_inventory_year = 2021, map_to = '458310' WHERE code = 44831;
UPDATE naics_code SET description = 'Jewelry Stores', last_inventory_year = 2021, map_to = '458310' WHERE code = 448310;
UPDATE naics_code SET description = 'All Other Telecommunications' WHERE code = 517810;
UPDATE naics_code SET description = 'Bituminous Coal Underground Mining', last_inventory_year = 2021, map_to = '212115' WHERE code = 212112;
UPDATE naics_code SET description = 'Anthracite Mining', last_inventory_year = 2021 WHERE code = 212113;
UPDATE naics_code SET description = 'Gold Ore Mining', last_inventory_year = 2021, map_to = '212220' WHERE code = 212221;
UPDATE naics_code SET description = 'Silver Ore Mining', last_inventory_year = 2021, map_to = '212220' WHERE code = 212222;
UPDATE naics_code SET description = 'All Other Metal Ore Mining', last_inventory_year = 2021, map_to = '212290' WHERE code = 212299;
UPDATE naics_code SET description = 'Kaolin and Ball Clay Mining', last_inventory_year = 2021, map_to = '212323' WHERE code = 212324;
UPDATE naics_code SET description = 'Libraries and Archives' WHERE code = 519210;
UPDATE naics_code SET description = 'Web Search Portals and All Other Information Services' WHERE code = 519290;
UPDATE naics_code SET description = 'Savings Institutions and Other Depository Credit Intermediation' WHERE code = 522180;
UPDATE naics_code SET description = 'International, Secondary Market, and All Other Nondepository Credit Intermediation' WHERE code = 522299;
UPDATE naics_code SET description = 'Investment Banking and Securities Intermediation' WHERE code = 523150;
UPDATE naics_code SET description = 'Commodity Contracts Intermediation' WHERE code = 523160;
UPDATE naics_code SET description = 'Portfolio Management and Investment Advice' WHERE code = 523940;
UPDATE naics_code SET description = 'Clothing and Clothing Accessories Retailers' WHERE code = 458110;
UPDATE naics_code SET description = 'Shoe Retailers' WHERE code = 458210;
UPDATE naics_code SET description = 'Jewelry Retailers' WHERE code = 458310;
UPDATE naics_code SET description = 'Luggage and Leather Goods Retailers' WHERE code = 458320;
UPDATE naics_code SET description = 'Sporting Goods Retailers' WHERE code = 459110;
UPDATE naics_code SET description = 'Hobby, Toy, and Game Retailers' WHERE code = 459120;
UPDATE naics_code SET description = 'Sewing, Needlework, and Piece Goods Retailers' WHERE code = 459130;
UPDATE naics_code SET description = 'Musical Instrument and Supplies Retailers' WHERE code = 459140;
UPDATE naics_code SET description = 'Book Retailers and News Dealers' WHERE code = 459210;
UPDATE naics_code SET description = 'Florists' WHERE code = 459310;
UPDATE naics_code SET description = 'Office Supplies and Stationery Retailers' WHERE code = 459410;
UPDATE naics_code SET description = 'Newspaper Publishers', last_inventory_year = 2021, map_to = '513110' WHERE code = 51111;
UPDATE naics_code SET description = 'Periodical Publishers', last_inventory_year = 2021, map_to = '513120' WHERE code = 511120;
UPDATE naics_code SET description = 'Gift, Novelty, and Souvenir Retailers' WHERE code = 459420;
UPDATE naics_code SET description = 'Used Merchandise Retailers' WHERE code = 459510;
UPDATE naics_code SET description = 'Pet and Pet Supplies Retailers' WHERE code = 459910;
UPDATE naics_code SET description = 'Art Dealers' WHERE code = 459920;
UPDATE naics_code SET description = 'Manufactured (Mobile) Home Dealers' WHERE code = 459930;
UPDATE naics_code SET description = 'Tobacco, Electronic Cigarette, and Other Smoking Supplies Retailers' WHERE code = 459991;
UPDATE naics_code SET description = 'All Other Miscellaneous Retailers' WHERE code = 459999;
UPDATE naics_code SET description = 'Specialized Automotive Repair' WHERE code = 811114;
UPDATE naics_code SET description = 'Electronic and Precision Equipment Repair and Maintenance' WHERE code = 811210;
UPDATE naics_code SET description = 'Support Activities for Mining', last_inventory_year = 2021, map_to = '21311' WHERE code = 2131;
UPDATE naics_code SET description = 'Nursery, Garden Center, and Farm Supply Stores', last_inventory_year = 2021, map_to = '444240' WHERE code = 44422;
UPDATE naics_code SET description = 'Supermarkets and Other Grocery Retailers (except Convenience Retailers)' WHERE code = 44511;
UPDATE naics_code SET description = 'Supermarkets and Other Grocery Retailers (except Convenience Retailers)' WHERE code = 445110;
UPDATE naics_code SET description = 'Meat Markets', last_inventory_year = 2021, map_to = '445240' WHERE code = 44521;
UPDATE naics_code SET description = 'Fish and Seafood Markets', last_inventory_year = 2021, map_to = '445250' WHERE code = 44522;
UPDATE naics_code SET description = 'Fish and Seafood Markets', last_inventory_year = 2021, map_to = '445250' WHERE code = 445220;
UPDATE naics_code SET description = 'Beer, Wine, and Liquor Stores', last_inventory_year = 2021, map_to = '445320' WHERE code = 44531;
UPDATE naics_code SET description = 'Beer, Wine, and Liquor Stores', last_inventory_year = 2021, map_to = '445320' WHERE code = 445310;
UPDATE naics_code SET description = 'Pharmacies and Drug Stores', last_inventory_year = 2021, map_to = '456110' WHERE code = 44611;
UPDATE naics_code SET description = 'Cosmetics, Beauty Supplies, and Perfume Stores', last_inventory_year = 2021, map_to = '456120' WHERE code = 44612;
UPDATE naics_code SET description = 'Cosmetics, Beauty Supplies, and Perfume Stores', last_inventory_year = 2021, map_to = '456120' WHERE code = 446120;
UPDATE naics_code SET description = 'Gasoline Stations with Convenience Stores', last_inventory_year = 2021, map_to = '457110' WHERE code = 44711;
UPDATE naics_code SET description = 'Gasoline Stations with Convenience Stores', last_inventory_year = 2021, map_to = '457110' WHERE code = 447110;
UPDATE naics_code SET description = 'Children''s and Infants'' Clothing Stores', last_inventory_year = 2021, map_to = '458110' WHERE code = 44813;
UPDATE naics_code SET description = 'Children''s and Infants'' Clothing Stores', last_inventory_year = 2021, map_to = '458110' WHERE code = 448130;
UPDATE naics_code SET description = 'Electronics and Appliance Retailers' WHERE code = 449210;
UPDATE naics_code SET description = 'Sewing, Needlework, and Piece Goods Stores', last_inventory_year = 2021, map_to = '459130' WHERE code = 45113;
UPDATE naics_code SET description = 'Sewing, Needlework, and Piece Goods Stores', last_inventory_year = 2021, map_to = '459130' WHERE code = 451130;
UPDATE naics_code SET description = 'Apparel Knitting Mills' WHERE code = 315120;
UPDATE naics_code SET description = 'All Other Publishers', last_inventory_year = 2021, map_to = '513199' WHERE code = 511199;
UPDATE naics_code SET description = 'Software Publishers', last_inventory_year = 2021, map_to = '513210' WHERE code = 5112;
UPDATE naics_code SET description = 'Radio and Television Broadcasting', last_inventory_year = 2021 WHERE code = 5151;
UPDATE naics_code SET description = 'Radio Broadcasting', last_inventory_year = 2021 WHERE code = 51511;
UPDATE naics_code SET description = 'Radio Networks', last_inventory_year = 2021, map_to = '516210' WHERE code = 515111;
UPDATE naics_code SET description = 'Wired and Wireless Telecommunications (except Satellite)' WHERE code = 5171;
UPDATE naics_code SET description = 'Wired and Wireless Telecommunications Carriers (except Satellite)' WHERE code = 51711;
UPDATE naics_code SET description = 'Telecommunications Resellers', last_inventory_year = 2021, map_to = '517121' WHERE code = 517911;
UPDATE naics_code SET description = 'Other Information Services', last_inventory_year = 2021 WHERE code = 5191;
UPDATE naics_code SET description = 'All Other Information Services', last_inventory_year = 2021, map_to = '519290' WHERE code = 51919;
UPDATE naics_code SET description = 'International Trade Financing', last_inventory_year = 2021, map_to = '522299' WHERE code = 522293;
UPDATE naics_code SET description = 'Secondary Market Financing', last_inventory_year = 2021, map_to = '522299' WHERE code = 522294;
UPDATE naics_code SET description = 'Investment Banking and Securities Dealing', last_inventory_year = 2021, map_to = '523150' WHERE code = 52311;
UPDATE naics_code SET description = 'Securities Brokerage', last_inventory_year = 2021, map_to = '523150' WHERE code = 523120;
UPDATE naics_code SET description = 'Portfolio Management', last_inventory_year = 2021, map_to = '523940' WHERE code = 52392;
UPDATE naics_code SET description = 'Pharmacy Benefit Management and Other Third Party Administration of Insurance and Pension Funds' WHERE code = 524292;
UPDATE naics_code SET description = 'Testing Laboratories and Services' WHERE code = 54138;
UPDATE naics_code SET description = 'Taxi and Ridesharing Services' WHERE code = 48531;
UPDATE naics_code SET description = 'Other Chemical and Fertilizer Mineral Mining', last_inventory_year = 2021, map_to = '212390' WHERE code = 212393;
UPDATE naics_code SET description = 'All Other Nonmetallic Mineral Mining', last_inventory_year = 2021, map_to = '212390' WHERE code = 212399;
UPDATE naics_code SET description = 'Newspaper, Periodical, Book, and Directory Publishers', last_inventory_year = 2021, map_to = '5131' WHERE code = 5111;
UPDATE naics_code SET description = 'Periodical Publishers', last_inventory_year = 2021, map_to = '513120' WHERE code = 51112;
UPDATE naics_code SET description = 'Other Publishers', last_inventory_year = 2021, map_to = '51319' WHERE code = 51119;
UPDATE naics_code SET description = 'Greeting Card Publishers', last_inventory_year = 2021, map_to = '513191' WHERE code = 511191;
UPDATE naics_code SET description = 'Automotive Exhaust System Repair', last_inventory_year = 2021, map_to = '811114' WHERE code = 811112;
UPDATE naics_code SET description = 'Automotive Transmission Repair', last_inventory_year = 2021, map_to = '811114' WHERE code = 811113;
UPDATE naics_code SET description = 'Newspaper Publishers', last_inventory_year = 2021, map_to = '513110' WHERE code = 511110;
UPDATE naics_code SET description = 'Book Publishers', last_inventory_year = 2021, map_to = '445132' WHERE code = 51113;
UPDATE naics_code SET description = 'Book Publishers', last_inventory_year = 2021, map_to = '513130' WHERE code = 511130;
UPDATE naics_code SET description = 'Directory and Mailing List Publishers', last_inventory_year = 2021, map_to = '513140' WHERE code = 51114;
UPDATE naics_code SET description = 'Tobacco Manufacturing', last_inventory_year = 2021, map_to = '312230' WHERE code = 31223;
UPDATE naics_code SET description = 'Hosiery and Sock Mills', last_inventory_year = 2021, map_to = '315120' WHERE code = 315110;
UPDATE naics_code SET description = 'Other Apparel Knitting Mills', last_inventory_year = 2021, map_to = '315120' WHERE code = 315190;
UPDATE naics_code SET description = 'Men''s and Boys'' Cut and Sew Apparel Manufacturing', last_inventory_year = 2021, map_to = '315250' WHERE code = 315220;
UPDATE naics_code SET description = 'Women''s, Girls'', and Infants'' Cut and Sew Apparel Manufacturing', last_inventory_year = 2021, map_to = '315250' WHERE code = 31524;
UPDATE naics_code SET description = 'Women''s, Girls'', and Infants'' Cut and Sew Apparel Manufacturing', last_inventory_year = 2021, map_to = '315250' WHERE code = 315240;
UPDATE naics_code SET description = 'Other Cut and Sew Apparel Manufacturing', last_inventory_year = 2021, map_to = '315250' WHERE code = 31528;
UPDATE naics_code SET description = 'Other Cut and Sew Apparel Manufacturing', last_inventory_year = 2021, map_to = '315250' WHERE code = 315280;
UPDATE naics_code SET description = 'All Other Leather Good and Allied Product Manufacturing', last_inventory_year = 2021, map_to = '316990' WHERE code = 316998;
UPDATE naics_code SET description = 'Compost Manufacturing' WHERE code = 325315;
UPDATE naics_code SET description = 'Motorcycle, ATV, and All Other Motor Vehicle Dealers' WHERE code = 441227;
UPDATE naics_code SET description = 'Automotive Parts and Accessories Retailers' WHERE code = 441330;
UPDATE naics_code SET description = 'Tire Dealers' WHERE code = 441340;
UPDATE naics_code SET description = 'Hardware Retailers' WHERE code = 444140;
UPDATE naics_code SET description = 'Other Building Material Dealers' WHERE code = 444180;
UPDATE naics_code SET description = 'Outdoor Power Equipment Retailers' WHERE code = 444230;
UPDATE naics_code SET description = 'Nursery, Garden Center, and Farm Supply Retailers' WHERE code = 444240;
UPDATE naics_code SET description = 'Convenience Retailers' WHERE code = 445131;
UPDATE naics_code SET description = 'Vending Machine Operators' WHERE code = 445132;
UPDATE naics_code SET description = 'Meat Retailers' WHERE code = 445240;
UPDATE naics_code SET description = 'Fish and Seafood Retailers' WHERE code = 445250;
UPDATE naics_code SET description = 'All Other Specialty Food Retailers' WHERE code = 445298;
UPDATE naics_code SET description = 'Beer, Wine, and Liquor Retailers' WHERE code = 445320;
UPDATE naics_code SET description = 'Furniture Retailers' WHERE code = 449110;
UPDATE naics_code SET description = 'Floor Covering Retailers' WHERE code = 449121;
UPDATE naics_code SET description = 'Window Treatment Retailers' WHERE code = 449122;
UPDATE naics_code SET description = 'All Other Home Furnishings Retailers' WHERE code = 449129;
UPDATE naics_code SET description = 'Surface Coal Mining' WHERE code = 212114;
UPDATE naics_code SET description = 'Underground Coal Mining' WHERE code = 212115;
UPDATE naics_code SET description = 'Gold Ore and Silver Ore Mining' WHERE code = 212220;
UPDATE naics_code SET description = 'Other Metal Ore Mining' WHERE code = 212290;
UPDATE naics_code SET description = 'Kaolin, Clay, and Ceramic and Refractory Minerals Mining' WHERE code = 212323;
UPDATE naics_code SET description = 'Other Nonmetallic Mineral Mining and Quarrying' WHERE code = 212390;
UPDATE naics_code SET description = 'Cut and Sew Apparel Manufacturing (except Contractors)' WHERE code = 315250;
UPDATE naics_code SET description = 'Other Leather and Allied Product Manufacturing' WHERE code = 316990;
UPDATE naics_code SET description = 'Engineered Wood Member Manufacturing' WHERE code = 321215;
UPDATE naics_code SET description = 'Paper Mills' WHERE code = 322120;
UPDATE naics_code SET description = 'Department Stores' WHERE code = 455110;
UPDATE naics_code SET description = 'Warehouse Clubs and Supercenters' WHERE code = 455211;
UPDATE naics_code SET description = 'All Other General Merchandise Retailers' WHERE code = 455219;
UPDATE naics_code SET description = 'Pharmacies and Drug Retailers' WHERE code = 456110;
UPDATE naics_code SET description = 'Cosmetics, Beauty Supplies, and Perfume Retailers' WHERE code = 456120;
UPDATE naics_code SET description = 'Optical Goods Retailers' WHERE code = 456130;
UPDATE naics_code SET description = 'Food (Health) Supplement Retailers' WHERE code = 456191;
UPDATE naics_code SET description = 'All Other Health and Personal Care Retailers' WHERE code = 456199;
UPDATE naics_code SET description = 'Gasoline Stations with Convenience Stores' WHERE code = 457110;
UPDATE naics_code SET description = 'Other Gasoline Stations' WHERE code = 457120;
UPDATE naics_code SET description = 'Fuel Dealers' WHERE code = 457210;
UPDATE naics_code SET description = 'All Other Industrial Machinery Manufacturing' WHERE code = 333248;
UPDATE naics_code SET description = 'Commercial and Service Industry Machinery Manufacturing' WHERE code = 333310;
UPDATE naics_code SET description = 'All Other Miscellaneous General Purpose Machinery Manufacturing' WHERE code = 333998;
UPDATE naics_code SET description = 'Manufacturing and Reproducing Magnetic and Optical Media' WHERE code = 334610;
UPDATE naics_code SET description = 'Residential Electric Lighting Fixture Manufacturing' WHERE code = 335131;
UPDATE naics_code SET description = 'Commercial, Industrial, and Institutional Electric Lighting Fixture Manufacturing' WHERE code = 335132;
UPDATE naics_code SET description = 'Electric Lamp Bulb and Other Lighting Equipment Manufacturing' WHERE code = 335139;
UPDATE naics_code SET description = 'Battery Manufacturing' WHERE code = 335910;
UPDATE naics_code SET description = 'Automobile and Light Duty Motor Vehicle Manufacturing' WHERE code = 336110;
UPDATE naics_code SET description = 'Household Furniture (except Wood and Upholstered) Manufacturing' WHERE code = 337126;
UPDATE naics_code SET description = 'Clothing and Clothing Accessories Merchant Wholesalers' WHERE code = 424350;
UPDATE naics_code SET description = 'Newspaper Publishers' WHERE code = 513110;
UPDATE naics_code SET description = 'Periodical Publishers' WHERE code = 513120;
UPDATE naics_code SET description = 'Book Publishers' WHERE code = 513130;
UPDATE naics_code SET description = 'Directory and Mailing List Publishers' WHERE code = 513140;
UPDATE naics_code SET description = 'Greeting Card Publishers' WHERE code = 513191;
UPDATE naics_code SET description = 'All Other Publishers' WHERE code = 513199;
UPDATE naics_code SET description = 'Software Publishers' WHERE code = 513210;
UPDATE naics_code SET description = 'Radio Broadcasting Stations' WHERE code = 516110;
UPDATE naics_code SET description = 'Television Broadcasting Stations' WHERE code = 516120;
UPDATE naics_code SET description = 'Media Streaming Distribution Services, Social Networks, and Other Media Networks and Content Providers' WHERE code = 516210;
UPDATE naics_code SET description = 'Wired Telecommunications Carriers' WHERE code = 517111;
UPDATE naics_code SET description = 'Wireless Telecommunications Carriers (except Satellite)' WHERE code = 517112;
UPDATE naics_code SET description = 'Telecommunications Resellers' WHERE code = 517121;
UPDATE naics_code SET description = 'Agents for Wireless Telecommunications Services' WHERE code = 517122;
UPDATE naics_code SET description = 'Potash, Soda, and Borate Mineral Mining', last_inventory_year = 2021, map_to = '212390' WHERE code = 212391;
UPDATE naics_code SET description = 'Phosphate Rock Mining', last_inventory_year = 2021, map_to = '212390' WHERE code = 212392;
UPDATE naics_code SET description = 'Paint and Wallpaper Retailers' WHERE code = 44412;
UPDATE naics_code SET description = 'Paint and Wallpaper Retailers' WHERE code = 444120;
UPDATE naics_code SET description = 'Hardware Stores', last_inventory_year = 2021, map_to = '444140' WHERE code = 44413;
UPDATE naics_code SET description = 'Women''s Handbag and Purse Manufacturing', last_inventory_year = 2021, map_to = '316990' WHERE code = 316992;
UPDATE naics_code SET description = 'Engineered Wood Member (except Truss) Manufacturing', last_inventory_year = 2021, map_to = '321215' WHERE code = 321213;
UPDATE naics_code SET description = 'Truss Manufacturing', last_inventory_year = 2021, map_to = '321215' WHERE code = 321214;
UPDATE naics_code SET description = 'Household Furniture (except Wood and Metal) Manufacturing', last_inventory_year = 2021, map_to = '337126' WHERE code = 337125;
UPDATE naics_code SET description = 'Other Lighting Equipment Manufacturing', last_inventory_year = 2021, map_to = '335139' WHERE code = 335129;
UPDATE naics_code SET description = 'Storage Battery Manufacturing', last_inventory_year = 2021, map_to = '335910' WHERE code = 335911;
UPDATE naics_code SET description = 'Primary Battery Manufacturing', last_inventory_year = 2021, map_to = '335910' WHERE code = 335912;
UPDATE naics_code SET description = 'Automobile Manufacturing', last_inventory_year = 2021, map_to = '336110' WHERE code = 336111;
UPDATE naics_code SET description = 'Light Truck and Utility Vehicle Manufacturing', last_inventory_year = 2021, map_to = '336110' WHERE code = 336112;
UPDATE naics_code SET description = 'Other Automotive Mechanical and Electrical Repair and Maintenance', last_inventory_year = 2021, map_to = '811114' WHERE code = 811118;
UPDATE naics_code SET description = 'All Other General Merchandise Stores', last_inventory_year = 2021, map_to = '455219' WHERE code = 452319;
UPDATE naics_code SET description = 'Electronic Shopping and Mail-Order Houses', last_inventory_year = 2021 WHERE code = 454110;
UPDATE naics_code SET description = 'Wired Telecommunications Carriers', last_inventory_year = 2021, map_to = '517111' WHERE code = 517311;
UPDATE naics_code SET description = 'Wireless Telecommunications Carriers (except Satellite)', last_inventory_year = 2021, map_to = '517112' WHERE code = 517312;
UPDATE naics_code SET description = 'Department Stores', last_inventory_year = 2021, map_to = '455110' WHERE code = 4522;
UPDATE naics_code SET description = 'Department Stores', last_inventory_year = 2021, map_to = '455110' WHERE code = 45221;
UPDATE naics_code SET description = 'General Merchandise Stores, including Warehouse Clubs and Supercenters', last_inventory_year = 2021, map_to = '45521' WHERE code = 4523;
UPDATE naics_code SET description = 'General Merchandise Stores, including Warehouse Clubs and Supercenters', last_inventory_year = 2021, map_to = '45521' WHERE code = 45231;
UPDATE naics_code SET description = 'Wired and Wireless Telecommunications Carriers', last_inventory_year = 2021, map_to = '51711' WHERE code = 5173;
UPDATE naics_code SET description = 'Wired and Wireless Telecommunications Carriers', last_inventory_year = 2021, map_to = '51711' WHERE code = 51731;
UPDATE naics_code SET description = 'Men''s and Boys'' Clothing and Furnishings Merchant Wholesalers', last_inventory_year = 2021, map_to = '424350' WHERE code = 42432;
UPDATE naics_code SET description = 'Men''s and Boys'' Clothing and Furnishings Merchant Wholesalers', last_inventory_year = 2021, map_to = '424350' WHERE code = 424320;
UPDATE naics_code SET description = 'Women''s, Children''s, and Infants'' Clothing and Accessories Merchant Wholesalers', last_inventory_year = 2021, map_to = '424350' WHERE code = 42433;
UPDATE naics_code SET description = 'Women''s, Children''s, and Infants'' Clothing and Accessories Merchant Wholesalers', last_inventory_year = 2021, map_to = '424350' WHERE code = 424330;
UPDATE naics_code SET description = 'Wet Corn Milling and Starch Manufacturing' WHERE code = 311221;
UPDATE naics_code SET description = 'All Other Telecommunications', last_inventory_year = 2021, map_to = '517810' WHERE code = 517919;
UPDATE naics_code SET description = 'News Syndicates', last_inventory_year = 2021, map_to = '516210' WHERE code = 51911;
UPDATE naics_code SET description = 'News Syndicates', last_inventory_year = 2021, map_to = '516210' WHERE code = 519110;
UPDATE naics_code SET description = 'Libraries and Archives', last_inventory_year = 2021, map_to = '519210' WHERE code = 51912;
UPDATE naics_code SET description = 'Libraries and Archives', last_inventory_year = 2021, map_to = '519210' WHERE code = 519120;
UPDATE naics_code SET description = 'Internet Publishing and Broadcasting and Web Search Portals', last_inventory_year = 2021 WHERE code = 51913;
UPDATE naics_code SET description = 'Internet Publishing and Broadcasting and Web Search Portals', last_inventory_year = 2021 WHERE code = 519130;
UPDATE naics_code SET description = 'All Other Information Services', last_inventory_year = 2021, map_to = '519290' WHERE code = 519190;
UPDATE naics_code SET description = 'Office Supplies and Stationery Stores', last_inventory_year = 2021, map_to = '459410' WHERE code = 45321;
UPDATE naics_code SET description = 'Gift, Novelty, and Souvenir Stores', last_inventory_year = 2021, map_to = '459420' WHERE code = 45322;
UPDATE naics_code SET description = 'Gift, Novelty, and Souvenir Stores', last_inventory_year = 2021, map_to = '459420' WHERE code = 453220;
UPDATE naics_code SET description = 'Used Merchandise Stores', last_inventory_year = 2021, map_to = '459510' WHERE code = 4533;
UPDATE naics_code SET description = 'Used Merchandise Stores', last_inventory_year = 2021, map_to = '459510' WHERE code = 453310;
UPDATE naics_code SET description = 'Manufactured (Mobile) Home Dealers', last_inventory_year = 2021, map_to = '459930' WHERE code = 45393;
UPDATE naics_code SET description = 'Manufactured (Mobile) Home Dealers', last_inventory_year = 2021, map_to = '459930' WHERE code = 453930;
UPDATE naics_code SET description = 'Computing Infrastructure Providers, Data Processing, Web Hosting, and Related Services' WHERE code = 5182;
UPDATE naics_code SET description = 'Computing Infrastructure Providers, Data Processing, Web Hosting, and Related Services' WHERE code = 51821;
UPDATE naics_code SET description = 'Computing Infrastructure Providers, Data Processing, Web Hosting, and Related Services' WHERE code = 518210;
UPDATE naics_code SET description = 'Consumer Electronics Repair and Maintenance', last_inventory_year = 2021, map_to = '811210' WHERE code = 811211;
UPDATE naics_code SET description = 'Computer and Office Machine Repair and Maintenance', last_inventory_year = 2021, map_to = '811210' WHERE code = 811212;
UPDATE naics_code SET description = 'Communication Equipment Repair and Maintenance', last_inventory_year = 2021, map_to = '811210' WHERE code = 811213;
UPDATE naics_code SET description = 'Other Electronic and Precision Equipment Repair and Maintenance', last_inventory_year = 2021, map_to = '811210' WHERE code = 811219;
UPDATE naics_code SET description = 'Other Apparel Knitting Mills', last_inventory_year = 2021, map_to = '315120' WHERE code = 31519;
UPDATE naics_code SET description = 'Savings Institutions', last_inventory_year = 2021, map_to = '522180' WHERE code = 52212;
UPDATE naics_code SET description = 'Savings Institutions', last_inventory_year = 2021, map_to = '522180' WHERE code = 522120;
UPDATE naics_code SET description = 'Other Depository Credit Intermediation', last_inventory_year = 2021, map_to = '522180' WHERE code = 52219;
UPDATE naics_code SET description = 'Other Depository Credit Intermediation', last_inventory_year = 2021, map_to = '522180' WHERE code = 522190;
UPDATE naics_code SET description = 'All Other Nondepository Credit Intermediation', last_inventory_year = 2021, map_to = '522299' WHERE code = 522298;
UPDATE naics_code SET description = 'Investment Banking and Securities Dealing', last_inventory_year = 2021, map_to = '523150' WHERE code = 523110;
UPDATE naics_code SET description = 'Securities Brokerage', last_inventory_year = 2021, map_to = '523150' WHERE code = 52312;
UPDATE naics_code SET description = 'Commodity Contracts Dealing', last_inventory_year = 2021, map_to = '523160' WHERE code = 52313;
UPDATE naics_code SET description = 'Commodity Contracts Dealing', last_inventory_year = 2021, map_to = '523160' WHERE code = 523130;
UPDATE naics_code SET description = 'Commodity Contracts Brokerage', last_inventory_year = 2021, map_to = '523160' WHERE code = 52314;
UPDATE naics_code SET description = 'Commodity Contracts Brokerage', last_inventory_year = 2021, map_to = '523160' WHERE code = 523140;
UPDATE naics_code SET description = 'Portfolio Management', last_inventory_year = 2021, map_to = '523940' WHERE code = 523920;
UPDATE naics_code SET description = 'Investment Advice', last_inventory_year = 2021, map_to = '523940' WHERE code = 52393;
UPDATE naics_code SET description = 'Investment Advice', last_inventory_year = 2021, map_to = '523940' WHERE code = 523930;
UPDATE naics_code SET description = 'Optical Instrument and Lens Manufacturing', last_inventory_year = 2021, map_to = '333310' WHERE code = 333314;
UPDATE naics_code SET description = 'Postal Service', last_inventory_year = 2021, map_to = '491110' WHERE code = 4911;
UPDATE naics_code SET description = 'Postal Service', last_inventory_year = 2021, map_to = '491110' WHERE code = 49111;
UPDATE naics_code SET description = 'Testing Laboratories and Services' WHERE code = 541380;

-- Pollutant
UPDATE pollutant SET last_inventory_year = 1900 WHERE pollutant_code = 'SO4';
UPDATE pollutant SET pollutant_name = 'PM Filterable', last_inventory_year = 2005 WHERE pollutant_code = 'PM-FIL';
UPDATE pollutant SET last_inventory_year = 1900 WHERE pollutant_code = 'NO3';
UPDATE pollutant SET last_inventory_year = 1900 WHERE pollutant_code = 'OC';
UPDATE pollutant SET last_inventory_year = 1900 WHERE pollutant_code = 'DIESEL-PM10';
UPDATE pollutant SET last_inventory_year = 1900 WHERE pollutant_code = 'DIESEL-PM25';
UPDATE pollutant SET last_inventory_year = 1900 WHERE pollutant_code = 'PMFINE';
UPDATE pollutant SET last_inventory_year = 1900 WHERE pollutant_code = 'EC';

-- Unit Measure Code
INSERT INTO unit_measure_code (code, description, ef_numerator, ef_denominator, unit_type, calculation_variable, legacy, unit_design_capacity, fuel_use_uom, heat_content_uom, fuel_use_type) VALUES ('BBTU', 'Billion BTUs', false, false, 'ENERGY', '[M] * [k] * btu', false, false, false, false, 'energy');
INSERT INTO unit_measure_code (code, description, ef_numerator, ef_denominator, unit_type, calculation_variable, legacy, unit_design_capacity, fuel_use_uom, heat_content_uom) VALUES ('F', 'DEGREES FAHRENHEIT', false, false, 'UNSUPPORTED', null, false, false, false, false);
INSERT INTO unit_measure_code (code, description, ef_numerator, ef_denominator, unit_type, calculation_variable, legacy, unit_design_capacity, fuel_use_uom, heat_content_uom) VALUES ('R', 'RANKINE', false, false, 'UNSUPPORTED', null, false, false, false, false);
INSERT INTO unit_measure_code (code, description, ef_numerator, ef_denominator, unit_type, calculation_variable, legacy, unit_design_capacity, fuel_use_uom, heat_content_uom) VALUES ('LB/E3GAL', 'POUNDS PER 1000 GALLONS', false, false, 'MASS/VOLUME', '[lb] / ([k] * [gall])', false, false, false, false);
INSERT INTO unit_measure_code (code, description, ef_numerator, ef_denominator, unit_type, calculation_variable, legacy, unit_design_capacity, fuel_use_uom, heat_content_uom) VALUES ('LB/IN2', 'POUNDS PER SQUARE INCH', false, false, 'MASS/AREA', '[lb] / ([inch] * [inch])', false, false, false, false);
INSERT INTO unit_measure_code (code, description, ef_numerator, ef_denominator, unit_type, calculation_variable, legacy, unit_design_capacity, fuel_use_uom, heat_content_uom) VALUES ('E3DOL', '1000 DOLLARS', false, false, 'UNSUPPORTED', null, false, false, false, false);

-- Coordinate Tolerance
UPDATE master_facility_record SET coordinate_tolerance = 0.08 WHERE eis_program_id = '863211';
UPDATE master_facility_record SET coordinate_tolerance = 0.003 WHERE eis_program_id = '1115011';
UPDATE master_facility_record SET coordinate_tolerance = 0.002 WHERE eis_program_id = '2534011';
UPDATE master_facility_record SET coordinate_tolerance = 0.0015 WHERE eis_program_id = '3699811';
UPDATE master_facility_record SET coordinate_tolerance = 0.0031 WHERE eis_program_id = '8354111';
UPDATE master_facility_record SET coordinate_tolerance = 0.003 WHERE eis_program_id = '17804811';
UPDATE master_facility_record SET coordinate_tolerance = 0.0025 WHERE eis_program_id = '17804911';
UPDATE master_facility_record SET coordinate_tolerance = 0.005 WHERE eis_program_id = '18984911';
