INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('CA', 'Coal ash content', 'PERCENT');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('CC', 'Coal carbon content', 'PERCENT');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('Cl', 'Fuel chlorine content', 'PERCENT');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('CS', 'Coal sulfur content', 'PERCENT');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('EQ', 'Equation based on fuel type (see NOTES)', 'REQUIRED');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('FA', 'Fuel ash content', 'PERCENT');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('FC', 'Fuel sulfur concentration', 'REQUIRED');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('FS', 'Fuel sulfur content', 'PERCENT');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('MS', 'Raw material sulfur content', 'PERCENT');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('si', 'Material silt content', 'PERCENT');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('Ti', 'Total yeast action time to the nearest tenth hr', 'REQUIRED');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('Ts', 'Spiking time to the nearest tenth (hr)', 'REQUIRED');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('Yf', 'Final (spike) baker''s percent of yeast', 'PERCENT');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('Yi', 'Initial baker''s percent of yeast', 'PERCENT');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('MR', 'Molar ratio of calcium to sulfur in the fluidized bed', 'REQUIRED');
INSERT INTO emission_formula_variable_code(code, description, validation_type) VALUES ('Na2O', 'Ash sodium content', 'PERCENT');
UPDATE emission_formula_variable_code SET description = 'Horizontal area, with blasting depth <= 70 ft' WHERE code = 'HA';
