delete from user_facility_association where master_facility_id in (select id from master_facility_record where program_system_code = 'RIDEM');

delete from release_point_appt where release_point_id in 
	(select rp.id from release_point rp join facility_site f on f.id = rp. facility_site_id join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from release_point where facility_site_id in 
	(select f.id from facility_site f join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from operating_detail where reporting_period_id in 
	(select rp.id from reporting_period rp join emissions_process p on rp.emissions_process_id = p.id
	join emissions_unit u on p.emissions_unit_id = u.id join facility_site f on f.id = u.facility_site_id join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from emission_formula_variable where emission_id in
	(select e.id from emission e join reporting_period rp on e.reporting_period_id = rp.id join emissions_process p on rp.emissions_process_id = p.id
	join emissions_unit u on p.emissions_unit_id = u.id join facility_site f on f.id = u.facility_site_id join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from emission where reporting_period_id in
	(select rp.id from reporting_period rp join emissions_process p on rp.emissions_process_id = p.id
	join emissions_unit u on p.emissions_unit_id = u.id join facility_site f on f.id = u.facility_site_id join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from reporting_period where emissions_process_id in 
	(select p.id from emissions_process p join emissions_unit u on p.emissions_unit_id = u.id join facility_site f on f.id = u.facility_site_id join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from emissions_process where emissions_unit_id in 
	(select u.id from emissions_unit u join facility_site f on f.id = u.facility_site_id join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from emissions_unit where facility_site_id in 
	(select f.id from facility_site f join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from facility_site_contact where facility_site_id in 
	(select f.id from facility_site f join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from control_pollutant where control_id in 
	(select c.id from control c join facility_site f on c.facility_site_id = f.id join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from control_assignment where control_id in 
	(select c.id from control c join facility_site f on c.facility_site_id = f.id join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from control where facility_site_id in 
	(select f.id from facility_site f join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from control_path_pollutant where control_path_id in 
	(select cp.id from control_path cp join facility_site f on cp.facility_site_id = f.id join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from control_path where facility_site_id in 
	(select f.id from facility_site f join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from facility_naics_xref where facility_site_id in 
	(select f.id from facility_site f join emissions_report er on er.id = f.report_id
	join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from facility_site where report_id in 
	(select er.id from emissions_report er join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from report_history where report_id in 
	(select er.id from emissions_report er join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from report_change where report_id in 
	(select er.id from emissions_report er join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from user_feedback where report_id in 
	(select er.id from emissions_report er join master_facility_record mfr on mfr.id = er.master_facility_id where mfr.program_system_code = 'RIDEM');  

delete from emissions_report where master_facility_id in (select id from master_facility_record where program_system_code = 'RIDEM');

delete from master_facility_naics_xref where master_facility_id in (select id from master_facility_record where program_system_code = 'RIDEM');

delete from master_facility_record where program_system_code = 'RIDEM';

insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('5456511','RIDEM','QUALITY SPRAYING TECHNOLOGIES','UNK',null,'OP','AIR1237','NA','2020','150 PARK LN','PROVIDENCE','44007','44','02907',null,'150 PARK LN','PROVIDENCE','44','02907',null,'41.7944','-71.4358',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('16390111','RIDEM','HONEYWELL SAFETY PRODUCTS USA, INC.',null,null,'OP','AIR4180','NA','2020','10 THURBER BLVD','SMITHFIELD','44007','44','02917',null,'10 THURBER BLVD','SMITHFIELD','44','02917',null,'41.911179','-71.517457',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('3089811','RIDEM','CRANSTON WPCF','UNK','105','OP','AIR1979','NA','2020','140 PETTACONSETT AVE','CRANSTON','44007','44','02920',null,'140 PETTACONSETT AVE','CRANSTON','44','02920',null,'41.75271','-71.4431',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('3036911','RIDEM','NAVAL STATION NEWPORT,CODE N8N','UNK','102','OP','AIR1044','NA','2020','1 SIMONPIETRI DR','NEWPORT','44005','44','02841',null,'1 SIMONPIETRI DR','NEWPORT','44','02841',null,'41.5274','-71.3084',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('2950111','RIDEM','RI RESOURCE RECOVERY CORPORATION','UNK','104','OP','AIR3860','NA','2020','65 SHUN PIKE','JOHNSTON','44007','44','02919',null,'65 SHUN PIKE','JOHNSTON','44','02919',null,'41.80512','-71.51825',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('6639711','RIDEM','ELECTRIC BOAT CORPORATION','UNK',null,'OP','AIR594','NA','2020','165 DILLABUR AVE','NORTH KINGSTOWN','44009','44','02852',null,'165 DILLABUR AVE','NORTH KINGSTOWN','44','02852',null,'41.59019','-71.42132',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('3040211','RIDEM','OCEAN STATE POWER','UNK','125','OP','AIR2998','NA','2020','1575 SHERMAN FARM RD','BURRILLVILLE','44007','44','02830',null,'1575 SHERMAN FARM RD','BURRILLVILLE','44','02830',null,'42.0099','-71.6701',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('17924111','RIDEM','TPI COMPOSITES, INC.',null,null,'OP','AIR4560','NA','2020','373 MARKET ST','WARREN','44001','44','02885',null,'373 MARKET ST','WARREN','44','02885',null,'41.749583','-71.270345',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('3109111','RIDEM','WOONSOCKET REGIONAL WASTEWATER COMMISSION','UNK','105','OP','AIR3269','NA','2020','11 CUMBERLAND HILL RD','WOONSOCKET','44007','44','02895',null,'11 CUMBERLAND HILL RD','WOONSOCKET','44','02895',null,'42.00002','-71.49521',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('5471311','RIDEM','R.I. CENTRAL POWER PLANT','UNK',null,'OP','AIR1248','NA','2020','15 POWER RD','CRANSTON','44007','44','02920',null,'15 POWER RD','CRANSTON','44','02920',null,'41.7445','-71.4584',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('5471811','RIDEM','RHODE ISLAND HOSPITAL','UNK','148','OP','AIR1283','NA','2020','593 EDDY ST','PROVIDENCE','44007','44','02903',null,'593 EDDY ST','PROVIDENCE','44','02903',null,'41.81148','-71.40724',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('6518611','RIDEM','EXXON MOBIL','HAP',null,'OP','AIR1003','NA','2020','1001 WAMPANOAG TRL','EAST PROVIDENCE','44007','44','02915',null,'1001 WAMPANOAG TRL','EAST PROVIDENCE','44','02915',null,'41.79449','-71.34931',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('3089311','RIDEM','BROWN UNIVERSITY','UNK','148','OP','AIR187','NA','2020','164 ANGELL ST','PROVIDENCE','44007','44','02912',null,'164 ANGELL ST','PROVIDENCE','44','02912',null,'41.82809','-71.40167',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('3075511','RIDEM','ALGONQUIN GAS TRANSMISSION CO.','UNK',null,'OP','AIR53','NA','2020','54 ALGONQUIN LN','BURRILLVILLE','44007','44','02830',null,'54 ALGONQUIN LN','BURRILLVILLE','44','02830',null,'41.9682','-71.7555',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('5460311','RIDEM','KENYON INDUSTRIES, INC.','HAP',null,'OP','AIR824','NA','2020','36 SHERMAN AVE','RICHMOND','44009','44','02836',null,'36 SHERMAN AVE','RICHMOND','44','02836',null,'41.44518','-71.62677',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('3038311','RIDEM','TIVERTON POWER','UNK','125','OP','AIR3810','NA','2020','304 PROGRESS RD','TIVERTON','44005','44','02878',null,'304 PROGRESS RD','TIVERTON','44','02878',null,'41.6417','-71.17',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('14955511','RIDEM','SAFETY-KLEEN SYSTEMS, INC.',null,null,'OP','AIR4022','NA','2020','167 MILL ST','CRANSTON','44007','44','02905',null,'167 MILL ST','CRANSTON','44','02905',null,'41.766457','-71.412694',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('5459911','RIDEM','SENESCO MARINE, LLC','UNK','182','OP','AIR3856','NA','2020','10 MACNAUGHT ST','NORTH KINGSTOWN','44009','44','02852',null,'10 MACNAUGHT ST','NORTH KINGSTOWN','44','02852',null,'41.58878','-71.41825',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('4105011','RIDEM','SHELL OIL PRODUCTS US','UNK',null,'OP','AIR1506','NA','2020','520 ALLENS AVE','PROVIDENCE','44007','44','02905',null,'520 ALLENS AVE','PROVIDENCE','44','02905',null,'41.79937','-71.39962',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('5486911','RIDEM','MANCHESTER STREET, LLC','HAP','125','OP','AIR936','NA','2020','40 POINT ST','PROVIDENCE','44007','44','02903',null,'40 POINT ST','PROVIDENCE','44','02903',null,'41.815719','-71.404042',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('6519711','RIDEM','DEWAL INDUSTRIES, INC.','UNK',null,'OP','AIR387','NA','2020','15 RAY TRAINOR DR','NARRAGANSETT','44009','44','02882',null,'15 RAY TRAINOR DR','NARRAGANSETT','44','02882',null,'41.48927','-71.42986',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('6519611','RIDEM','TORAY PLASTICS AMERICA, INC.','UNK','173','OP','AIR3052','NA','2020','50 BELVER AVE','NORTH KINGSTOWN','44009','44','02852',null,'50 BELVER AVE','NORTH KINGSTOWN','44','02852',null,'41.5939','-71.4267',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('4800811','RIDEM','THE ORIGINAL BRADFORD SOAP WORKS, INC.','UNK',null,'OP','AIR1846','NA','2020','200 PROVIDENCE ST','WEST WARWICK','44003','44','02893',null,'200 PROVIDENCE ST','WEST WARWICK','44','02893',null,'41.71416','-71.51347',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('5458211','RIDEM','UNIVERSITY OF RHODE ISLAND/CONTIGUOUS','UNK','148','OP','AIR1584','NA','2020','523 PLAINS RD','SOUTH KINGSTOWN','44009','44','02881',null,'523 PLAINS RD','SOUTH KINGSTOWN','44','02881',null,'41.48846','-71.54261',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('2968111','RIDEM','PROVIDENCE METALLIZING CO., INC.','UNK',null,'OP','AIR1230','NA','2020','51 FAIRLAWN AVE','PAWTUCKET','44007','44','02860',null,'51 FAIRLAWN AVE','PAWTUCKET','44','02860',null,'41.87169','-71.41236',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('3073211','RIDEM','RHODE ISLAND STATE ENERGY CENTER','UNK','125','OP','AIR3914','NA','2020','24 SHUN PIKE','JOHNSTON','44007','44','02919',null,'24 SHUN PIKE','JOHNSTON','44','02919',null,'41.8017','-71.5186',null,'SYSTEM','SYSTEM',NOW());
insert into master_facility_record (eis_program_id, program_system_code, name, category_code, source_type_code, status_code, agency_facility_id, description, status_year, street_address, city, county_code, state_code, postal_code, country_code, mailing_street_address, mailing_city, mailing_state_code, mailing_postal_code, mailing_country_code, latitude, longitude, tribal_code, created_by, last_modified_by, last_modified_date) VALUES('3109711','RIDEM','RHODE ISLAND LFG GENCO, LLC','UNK','125','OP','AIR3295','NA','2020','40 SHUN PIKE','JOHNSTON','44007','44','02919',null,'40 SHUN PIKE','JOHNSTON','44','02919',null,'41.8032','-71.5238',null,'SYSTEM','SYSTEM',NOW());