UPDATE unit_measure_code
SET description = 'THOUSAND DRY STANDARD CUBIC FEET'
WHERE code = 'E3FT3SD';

UPDATE program_system_code
SET description = 'Asheville-Buncombe Air Quality Agency'
WHERE code = 'NCBCRAQA';

INSERT INTO program_system_code (code, description)
VALUES ('EPA_R08', 'EPA Region 8');

INSERT INTO facility_source_type_code (code, description, last_inventory_year)
VALUES ('186', 'Tire Plant', null);

INSERT INTO facility_source_type_code (code, description, last_inventory_year)
VALUES ('187', 'Wood Pellet Plant', null);

INSERT INTO facility_source_type_code (code, description, last_inventory_year)
VALUES ('188', 'Commercial Sterilizer', null);

UPDATE master_facility_record
SET coordinate_tolerance = 0.002
WHERE eis_program_id IN ('6518611', '18957811');

UPDATE master_facility_record
SET coordinate_tolerance = 0.003
WHERE eis_program_id IN ('18956511', '18956711', '18956811', '18956911', '18957411', '18957511', '18957611', '18957711', '18962211');

UPDATE master_facility_record
SET coordinate_tolerance = 0.005
WHERE eis_program_id = '1819311';

UPDATE master_facility_record
SET coordinate_tolerance = 0.0071
WHERE eis_program_id  = '16983411';

UPDATE pollutant SET pollutant_name = 'Acrylamide', last_inventory_year = NULL, pollutant_srs_id = '7575', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '79061';
UPDATE pollutant SET pollutant_name = 'Toxaphene', last_inventory_year = NULL, pollutant_srs_id = '156919', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '8001352';
UPDATE pollutant SET pollutant_name = 'Methyl Methacrylate', last_inventory_year = NULL, pollutant_srs_id = '8458', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '80626';
UPDATE pollutant SET pollutant_name = 'Pentachloronitrobenzene', last_inventory_year = NULL, pollutant_srs_id = '9373', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '82688';
UPDATE pollutant SET pollutant_name = 'Hexane', last_inventory_year = NULL, pollutant_srs_id = '26740', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '110543';
UPDATE pollutant SET pollutant_name = '1,2-Dimethoxyethane', last_inventory_year = NULL, pollutant_srs_id = '26906', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '110714';
UPDATE pollutant SET pollutant_name = 'Cellosolve Acetate', last_inventory_year = NULL, pollutant_srs_id = '27284', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '111159';
UPDATE pollutant SET pollutant_name = 'Carbitol Acetate', last_inventory_year = NULL, pollutant_srs_id = '28167', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '112152';
UPDATE pollutant SET pollutant_name = 'Ethoxytriglycol', last_inventory_year = NULL, pollutant_srs_id = '28480', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '112505';
UPDATE pollutant SET pollutant_name = 'Propoxur', last_inventory_year = NULL, pollutant_srs_id = '28928', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '114261';
UPDATE pollutant SET pollutant_name = 'Bis(2-Ethylhexyl)Phthalate', last_inventory_year = NULL, pollutant_srs_id = '29934', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '117817';
UPDATE pollutant SET pollutant_name = 'Anthracene', last_inventory_year = NULL, pollutant_srs_id = '31013', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '120127';
UPDATE pollutant SET pollutant_name = 'Chlorobenzilate', last_inventory_year = NULL, pollutant_srs_id = '49320', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '510156';
UPDATE pollutant SET pollutant_name = '2,4-Dinitrophenol', last_inventory_year = NULL, pollutant_srs_id = '1313', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '51285';
UPDATE pollutant SET pollutant_name = '2-Acetylaminofluorene', last_inventory_year = NULL, pollutant_srs_id = '1719', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '53963';
UPDATE pollutant SET pollutant_name = '1,3-Dichloropropene', last_inventory_year = NULL, pollutant_srs_id = '52449', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '542756';
UPDATE pollutant SET pollutant_name = 'Benzofluoranthenes', last_inventory_year = NULL, pollutant_srs_id = '308023', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '56832736';
UPDATE pollutant SET pollutant_name = 'Chloroform', last_inventory_year = NULL, pollutant_srs_id = '4317', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '67663';
UPDATE pollutant SET pollutant_name = 'Hexachloroethane', last_inventory_year = NULL, pollutant_srs_id = '4341', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '67721';
UPDATE pollutant SET pollutant_name = 'Hexamethylphosphoramide', last_inventory_year = NULL, pollutant_srs_id = '67314', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '680319';
UPDATE pollutant SET pollutant_name = 'Uranium-238', last_inventory_year = NULL, pollutant_srs_id = '150185', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7440611';
UPDATE pollutant SET pollutant_name = 'Acetonitrile', last_inventory_year = NULL, pollutant_srs_id = '5272', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '75058';
UPDATE pollutant SET pollutant_name = 'Ethylene Oxide', last_inventory_year = NULL, pollutant_srs_id = '5405', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '75218';
UPDATE pollutant SET pollutant_name = 'Vinylidene Chloride', last_inventory_year = NULL, pollutant_srs_id = '5538', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '75354';
UPDATE pollutant SET pollutant_name = 'Heptachlor', last_inventory_year = NULL, pollutant_srs_id = '6262', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '76448';
UPDATE pollutant SET pollutant_name = 'Hexachlorocyclopentadiene', last_inventory_year = NULL, pollutant_srs_id = '6494', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '77474';
UPDATE pollutant SET pollutant_name = 'Dimethyl Sulfate', last_inventory_year = NULL, pollutant_srs_id = '6684', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '77781';
UPDATE pollutant SET pollutant_name = 'Chlorine', last_inventory_year = NULL, pollutant_srs_id = '154328', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7782505';
UPDATE pollutant SET pollutant_name = 'Benzo[g,h,i,]Perylene', last_inventory_year = NULL, pollutant_srs_id = '40576', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '191242';
UPDATE pollutant SET pollutant_name = 'Hydrogen Sulfide', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'OTH', pollutant_standard_uom_code = 'LB' where pollutant_code = '7783064';
UPDATE pollutant SET pollutant_name = 'Organic Carbon portion of PM2.5-PRI', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'OTH', pollutant_standard_uom_code = 'TON' where pollutant_code = 'OC';
UPDATE pollutant SET pollutant_name = 'PM10-Primary from certain diesel engines', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'OTH', pollutant_standard_uom_code = 'TON' where pollutant_code = 'DIESEL-PM10';
UPDATE pollutant SET pollutant_name = 'PM25-Primary from certain diesel engines', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'OTH', pollutant_standard_uom_code = 'TON' where pollutant_code = 'DIESEL-PM25';
UPDATE pollutant SET pollutant_name = 'Remaining PMFINE portion of PM2.5-PRI', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'OTH', pollutant_standard_uom_code = 'TON' where pollutant_code = 'PMFINE';
UPDATE pollutant SET pollutant_name = 'Ethyl Benzene', last_inventory_year = NULL, pollutant_srs_id = '19406', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '100414';
UPDATE pollutant SET pollutant_name = 'Benzyl Chloride', last_inventory_year = NULL, pollutant_srs_id = '19430', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '100447';
UPDATE pollutant SET pollutant_name = '4,4''-Methylenediphenyl Diisocyanate', last_inventory_year = NULL, pollutant_srs_id = '20263', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '101688';
UPDATE pollutant SET pollutant_name = 'p-Xylene', last_inventory_year = NULL, pollutant_srs_id = '23580', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '106423';
UPDATE pollutant SET pollutant_name = '1,4-Dichlorobenzene', last_inventory_year = NULL, pollutant_srs_id = '23622', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '106467';
UPDATE pollutant SET pollutant_name = 'Quinone', last_inventory_year = NULL, pollutant_srs_id = '23671', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '106514';
UPDATE pollutant SET pollutant_name = '1,2-Epoxybutane', last_inventory_year = NULL, pollutant_srs_id = '23937', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '106887';
UPDATE pollutant SET pollutant_name = 'Acrolein', last_inventory_year = NULL, pollutant_srs_id = '24075', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '107028';
UPDATE pollutant SET pollutant_name = 'Allyl Chloride', last_inventory_year = NULL, pollutant_srs_id = '24109', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '107051';
UPDATE pollutant SET pollutant_name = 'Vinyl Acetate', last_inventory_year = NULL, pollutant_srs_id = '24828', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '108054';
UPDATE pollutant SET pollutant_name = 'm-Xylene', last_inventory_year = NULL, pollutant_srs_id = '25056', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '108383';
UPDATE pollutant SET pollutant_name = 'Toluene', last_inventory_year = NULL, pollutant_srs_id = '25452', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '108883';
UPDATE pollutant SET pollutant_name = 'Phenol', last_inventory_year = NULL, pollutant_srs_id = '25510', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '108952';
UPDATE pollutant SET pollutant_name = 'Ethylene Glycol Methyl Ether', last_inventory_year = NULL, pollutant_srs_id = '26211', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '109864';
UPDATE pollutant SET pollutant_name = 'Cellosolve Solvent', last_inventory_year = NULL, pollutant_srs_id = '26989', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '110805';
UPDATE pollutant SET pollutant_name = 'Diethanolamine', last_inventory_year = NULL, pollutant_srs_id = '27516', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '111422';
UPDATE pollutant SET pollutant_name = 'Diethylene Glycol Monomethyl Ether', last_inventory_year = NULL, pollutant_srs_id = '27854', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '111773';
UPDATE pollutant SET pollutant_name = '1,3-Propanesultone', last_inventory_year = NULL, pollutant_srs_id = '79012', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '1120714';
UPDATE pollutant SET pollutant_name = '2-Butoxyethyl Acetate', last_inventory_year = NULL, pollutant_srs_id = '28100', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '112072';
UPDATE pollutant SET pollutant_name = 'Diethylene Glycol Monobutyl Ether', last_inventory_year = NULL, pollutant_srs_id = '28340', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '112345';
UPDATE pollutant SET pollutant_name = 'Methoxytriglycol', last_inventory_year = NULL, pollutant_srs_id = '28357', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '112356';
UPDATE pollutant SET pollutant_name = 'N-Hexyl Carbitol', last_inventory_year = NULL, pollutant_srs_id = '28563', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '112594';
UPDATE pollutant SET pollutant_name = 'Hexachlorobenzene', last_inventory_year = NULL, pollutant_srs_id = '30346', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '118741';
UPDATE pollutant SET pollutant_name = 'Formaldehyde', last_inventory_year = NULL, pollutant_srs_id = '1008', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '50000';
UPDATE pollutant SET pollutant_name = 'Ethyl Carbamate', last_inventory_year = NULL, pollutant_srs_id = '1495', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '51796';
UPDATE pollutant SET pollutant_name = '4,6-Dinitro-o-Cresol', last_inventory_year = NULL, pollutant_srs_id = '51102', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '534521';
UPDATE pollutant SET pollutant_name = 'Tert-butyl Acetate', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'OTH', pollutant_standard_uom_code = 'LB' where pollutant_code = '540885';
UPDATE pollutant SET pollutant_name = 'Parathion', last_inventory_year = NULL, pollutant_srs_id = '2147', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '56382';
UPDATE pollutant SET pollutant_name = 'Benz[a]Anthracene', last_inventory_year = NULL, pollutant_srs_id = '2212', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '56553';
UPDATE pollutant SET pollutant_name = '1,1-Dimethyl Hydrazine', last_inventory_year = NULL, pollutant_srs_id = '2469', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '57147';
UPDATE pollutant SET pollutant_name = 'Ethylene Glycol Monomethyl Ether Acetate', last_inventory_year = NULL, pollutant_srs_id = '26708', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '110496';
UPDATE pollutant SET pollutant_name = 'Dichloroethyl Ether', last_inventory_year = NULL, pollutant_srs_id = '27532', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '111444';
UPDATE pollutant SET pollutant_name = 'Diethylene Glycol Monoethyl Ether', last_inventory_year = NULL, pollutant_srs_id = '27979', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '111900';
UPDATE pollutant SET pollutant_name = '2-(Hexyloxy)Ethanol', last_inventory_year = NULL, pollutant_srs_id = '28266', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '112254';
UPDATE pollutant SET pollutant_name = 'Diethylene Glycol Diethyl Ether', last_inventory_year = NULL, pollutant_srs_id = '28365', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '112367';
UPDATE pollutant SET pollutant_name = '2,4-Dinitrotoluene', last_inventory_year = NULL, pollutant_srs_id = '31575', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '121142';
UPDATE pollutant SET pollutant_name = 'N,N-Dimethylaniline', last_inventory_year = NULL, pollutant_srs_id = '31880', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '121697';
UPDATE pollutant SET pollutant_name = 'Propionaldehyde', last_inventory_year = NULL, pollutant_srs_id = '32953', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '123386';
UPDATE pollutant SET pollutant_name = 'N-Nitroso-N-Methylurea', last_inventory_year = NULL, pollutant_srs_id = '67462', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '684935';
UPDATE pollutant SET pollutant_name = 'Triglycol Monobutyl Ether', last_inventory_year = NULL, pollutant_srs_id = '39248', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '143226';
UPDATE pollutant SET pollutant_name = 'Chromium III', last_inventory_year = NULL, pollutant_srs_id = '203000', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '16065831';
UPDATE pollutant SET pollutant_name = 'Glycol Ethers', last_inventory_year = NULL, pollutant_srs_id = '649996', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '171';
UPDATE pollutant SET pollutant_name = 'Chromium (VI)', last_inventory_year = NULL, pollutant_srs_id = '212357', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '18540299';
UPDATE pollutant SET pollutant_name = 'Benzotrichloride', last_inventory_year = NULL, pollutant_srs_id = '17756', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '98077';
UPDATE pollutant SET pollutant_name = 'Nitrobenzene', last_inventory_year = NULL, pollutant_srs_id = '18408', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '98953';
UPDATE pollutant SET pollutant_name = 'Cresol/Cresylic Acid (Mixed Isomers)', last_inventory_year = NULL, pollutant_srs_id = '83550', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '1319773';
UPDATE pollutant SET pollutant_name = '2-Chloroacetophenone', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '532274';
UPDATE pollutant SET pollutant_name = '2,2,4-Trimethylpentane', last_inventory_year = NULL, pollutant_srs_id = '51961', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '540841';
UPDATE pollutant SET pollutant_name = '3-Methylcholanthrene', last_inventory_year = NULL, pollutant_srs_id = '2188', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '56495';
UPDATE pollutant SET pollutant_name = '4-Dimethylaminoazobenzene', last_inventory_year = NULL, pollutant_srs_id = '3269', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '60117';
UPDATE pollutant SET pollutant_name = 'Tetrachlorobiphenyl', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '26914330';
UPDATE pollutant SET pollutant_name = 'p-Cresol', last_inventory_year = NULL, pollutant_srs_id = '23606', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '106445';
UPDATE pollutant SET pollutant_name = 'Chloromethyl Methyl Ether', last_inventory_year = NULL, pollutant_srs_id = '24299', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '107302';
UPDATE pollutant SET pollutant_name = 'Carbon Monoxide', last_inventory_year = NULL, pollutant_srs_id = '65052', pollutant_type = 'CAP', pollutant_standard_uom_code = 'TON' where pollutant_code = 'CO';
UPDATE pollutant SET pollutant_name = 'Nitrogen Oxides', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'CAP', pollutant_standard_uom_code = 'TON' where pollutant_code = 'NOX';
UPDATE pollutant SET pollutant_name = 'PM2.5 Primary (Filt + Cond)', last_inventory_year = NULL, pollutant_srs_id = '524672300', pollutant_type = 'CAP', pollutant_standard_uom_code = 'TON' where pollutant_code = 'PM25-PRI';
UPDATE pollutant SET pollutant_name = 'Volatile Organic Compounds', last_inventory_year = NULL, pollutant_srs_id = '761346', pollutant_type = 'CAP', pollutant_standard_uom_code = 'TON' where pollutant_code = 'VOC';
UPDATE pollutant SET pollutant_name = 'Heptachlorobiphenyl', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '28655712';
UPDATE pollutant SET pollutant_name = 'Hydrazine', last_inventory_year = NULL, pollutant_srs_id = '41541', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '302012';
UPDATE pollutant SET pollutant_name = 'Hydroquinone', last_inventory_year = NULL, pollutant_srs_id = '32904', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '123319';
UPDATE pollutant SET pollutant_name = 'Butyl Carbitol Acetate', last_inventory_year = NULL, pollutant_srs_id = '33449', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '124174';
UPDATE pollutant SET pollutant_name = 'PAH, total', last_inventory_year = NULL, pollutant_srs_id = '627059', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '130498292';
UPDATE pollutant SET pollutant_name = 'Dibenzofuran', last_inventory_year = NULL, pollutant_srs_id = '35709', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '132649';
UPDATE pollutant SET pollutant_name = 'Captan', last_inventory_year = NULL, pollutant_srs_id = '35790', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '133062';
UPDATE pollutant SET pollutant_name = 'Asbestos', last_inventory_year = NULL, pollutant_srs_id = '85282', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '1332214';
UPDATE pollutant SET pollutant_name = 'Chloramben', last_inventory_year = NULL, pollutant_srs_id = '35956', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '133904';
UPDATE pollutant SET pollutant_name = 'Ethyl Acrylate', last_inventory_year = NULL, pollutant_srs_id = '37929', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '140885';
UPDATE pollutant SET pollutant_name = 'Propylene Dichloride', last_inventory_year = NULL, pollutant_srs_id = '7393', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '78875';
UPDATE pollutant SET pollutant_name = 'Coal Tar', last_inventory_year = NULL, pollutant_srs_id = '157958', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '8007452';
UPDATE pollutant SET pollutant_name = 'Phenanthrene', last_inventory_year = NULL, pollutant_srs_id = '10199', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '85018';
UPDATE pollutant SET pollutant_name = 'Fluorene', last_inventory_year = NULL, pollutant_srs_id = '10892', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '86737';
UPDATE pollutant SET pollutant_name = 'Carbazole', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '86748';
UPDATE pollutant SET pollutant_name = 'Hexachlorobutadiene', last_inventory_year = NULL, pollutant_srs_id = '11346', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '87683';
UPDATE pollutant SET pollutant_name = 'Pentachlorophenol', last_inventory_year = NULL, pollutant_srs_id = '11437', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '87865';
UPDATE pollutant SET pollutant_name = '2,4,6-Trichlorophenol', last_inventory_year = NULL, pollutant_srs_id = '11536', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '88062';
UPDATE pollutant SET pollutant_name = 'o-Anisidine', last_inventory_year = NULL, pollutant_srs_id = '12815', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '90040';
UPDATE pollutant SET pollutant_name = 'Naphthalene', last_inventory_year = NULL, pollutant_srs_id = '13326', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '91203';
UPDATE pollutant SET pollutant_name = 'Quinoline', last_inventory_year = NULL, pollutant_srs_id = '13342', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '91225';
UPDATE pollutant SET pollutant_name = '2-Chloronaphthalene', last_inventory_year = NULL, pollutant_srs_id = '13532', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '91587';
UPDATE pollutant SET pollutant_name = '3,3''-Dichlorobenzidine', last_inventory_year = NULL, pollutant_srs_id = '13755', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '91941';
UPDATE pollutant SET pollutant_name = 'Biphenyl', last_inventory_year = NULL, pollutant_srs_id = '14183', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '92524';
UPDATE pollutant SET pollutant_name = '4-Aminobiphenyl', last_inventory_year = NULL, pollutant_srs_id = '14308', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '92671';
UPDATE pollutant SET pollutant_name = 'Benzidine', last_inventory_year = NULL, pollutant_srs_id = '14498', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '92875';
UPDATE pollutant SET pollutant_name = '4-Nitrobiphenyl', last_inventory_year = NULL, pollutant_srs_id = '14548', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '92933';
UPDATE pollutant SET pollutant_name = 'o-Toluidine', last_inventory_year = NULL, pollutant_srs_id = '16196', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '95534';
UPDATE pollutant SET pollutant_name = 'Toluene-2,4-Diamine', last_inventory_year = NULL, pollutant_srs_id = '16410', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '95807';
UPDATE pollutant SET pollutant_name = 'Styrene Oxide', last_inventory_year = NULL, pollutant_srs_id = '16584', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '96093';
UPDATE pollutant SET pollutant_name = '1,2-Dibromo-3-Chloropropane', last_inventory_year = NULL, pollutant_srs_id = '16618', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '96128';
UPDATE pollutant SET pollutant_name = 'Ethylene Thiourea', last_inventory_year = NULL, pollutant_srs_id = '16857', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '96457';
UPDATE pollutant SET pollutant_name = 'Cumene', last_inventory_year = NULL, pollutant_srs_id = '18309', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '98828';
UPDATE pollutant SET pollutant_name = 'PM10 Filterable', last_inventory_year = NULL, pollutant_srs_id = '524672276', pollutant_type = 'CAP', pollutant_standard_uom_code = 'TON' where pollutant_code = 'PM10-FIL';
UPDATE pollutant SET pollutant_name = 'PM10 Primary (Filt + Cond)', last_inventory_year = NULL, pollutant_srs_id = '524672284', pollutant_type = 'CAP', pollutant_standard_uom_code = 'TON' where pollutant_code = 'PM10-PRI';
UPDATE pollutant SET pollutant_name = 'PM2.5 Filterable', last_inventory_year = NULL, pollutant_srs_id = '524672292', pollutant_type = 'CAP', pollutant_standard_uom_code = 'TON' where pollutant_code = 'PM25-FIL';
UPDATE pollutant SET pollutant_name = 'PM Condensible', last_inventory_year = NULL, pollutant_srs_id = '524672318', pollutant_type = 'CAP', pollutant_standard_uom_code = 'TON' where pollutant_code = 'PM-CON';
UPDATE pollutant SET pollutant_name = 'Sulfur Dioxide', last_inventory_year = NULL, pollutant_srs_id = '150367', pollutant_type = 'CAP', pollutant_standard_uom_code = 'TON' where pollutant_code = 'SO2';
UPDATE pollutant SET pollutant_name = 'Benzo[a]Pyrene', last_inventory_year = NULL, pollutant_srs_id = '1115', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '50328';
UPDATE pollutant SET pollutant_name = 'Bis(Chloromethyl)Ether', last_inventory_year = NULL, pollutant_srs_id = '52498', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '542881';
UPDATE pollutant SET pollutant_name = 'Cyanide', last_inventory_year = NULL, pollutant_srs_id = '2444', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '57125';
UPDATE pollutant SET pollutant_name = 'N-Nitrosomorpholine', last_inventory_year = NULL, pollutant_srs_id = '3194', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '59892';
UPDATE pollutant SET pollutant_name = 'Rockwool (Man-Made Fibers)', last_inventory_year = NULL, pollutant_srs_id = '649533', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '617';
UPDATE pollutant SET pollutant_name = '4,4''-Methylenebis(2-Chloraniline)', last_inventory_year = NULL, pollutant_srs_id = '19943', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '101144';
UPDATE pollutant SET pollutant_name = 'Elemental Carbon portion of PM2.5-PRI', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'OTH', pollutant_standard_uom_code = 'TON' where pollutant_code = 'EC';
UPDATE pollutant SET pollutant_name = '4,4''-Dichlorobiphenyl (PCB-15)', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '2050682';
UPDATE pollutant SET pollutant_name = '2-Chlorobiphenyl (PCB-1)', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '2051607';
UPDATE pollutant SET pollutant_name = 'Benzo[j]fluoranthene', last_inventory_year = NULL, pollutant_srs_id = '40675', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '205823';
UPDATE pollutant SET pollutant_name = '2-Propoxyethyl Acetate', last_inventory_year = NULL, pollutant_srs_id = '650762', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '20706256';
UPDATE pollutant SET pollutant_name = 'Acenaphthylene', last_inventory_year = NULL, pollutant_srs_id = '40717', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '208968';
UPDATE pollutant SET pollutant_name = '15-PAH', last_inventory_year = 2005, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '249';
UPDATE pollutant SET pollutant_name = 'Pentachlorobiphenyl', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '25429292';
UPDATE pollutant SET pollutant_name = 'Hexachlorobiphenyl', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '26601649';
UPDATE pollutant SET pollutant_name = 'Methylanthracene', last_inventory_year = NULL, pollutant_srs_id = '52450418', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '26914181';
UPDATE pollutant SET pollutant_name = 'Propyl Cellosolve', last_inventory_year = NULL, pollutant_srs_id = '107573', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '2807309';
UPDATE pollutant SET pollutant_name = 'Extractable Organic Matter (EOM)', last_inventory_year = 2016, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '284';
UPDATE pollutant SET pollutant_name = '5-Methylchrysene', last_inventory_year = NULL, pollutant_srs_id = '118240', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '3697243';
UPDATE pollutant SET pollutant_name = 'Catechol', last_inventory_year = NULL, pollutant_srs_id = '31427', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '120809';
UPDATE pollutant SET pollutant_name = 'Triethylamine', last_inventory_year = NULL, pollutant_srs_id = '31708', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '121448';
UPDATE pollutant SET pollutant_name = '1,2-Diphenylhydrazine', last_inventory_year = NULL, pollutant_srs_id = '32425', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '122667';
UPDATE pollutant SET pollutant_name = 'Phenyl Cellosolve', last_inventory_year = NULL, pollutant_srs_id = '32664', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '122996';
UPDATE pollutant SET pollutant_name = 'p-Dioxane', last_inventory_year = NULL, pollutant_srs_id = '33241', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '123911';
UPDATE pollutant SET pollutant_name = 'Pyrene', last_inventory_year = NULL, pollutant_srs_id = '34843', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '129000';
UPDATE pollutant SET pollutant_name = 'Nickel Oxide', last_inventory_year = NULL, pollutant_srs_id = '82891', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '1313991';
UPDATE pollutant SET pollutant_name = 'Chromium Trioxide', last_inventory_year = 2022, pollutant_srs_id = '85571', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '1333820';
UPDATE pollutant SET pollutant_name = 'Nickel', last_inventory_year = NULL, pollutant_srs_id = '149674', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7440020';
UPDATE pollutant SET pollutant_name = 'Antimony', last_inventory_year = NULL, pollutant_srs_id = '149963', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7440360';
UPDATE pollutant SET pollutant_name = 'Beryllium', last_inventory_year = NULL, pollutant_srs_id = '150003', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7440417';
UPDATE pollutant SET pollutant_name = 'Cobalt', last_inventory_year = NULL, pollutant_srs_id = '150078', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7440484';
UPDATE pollutant SET pollutant_name = 'Methyl Bromide', last_inventory_year = NULL, pollutant_srs_id = '5074', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '74839';
UPDATE pollutant SET pollutant_name = 'Methyl Iodide', last_inventory_year = NULL, pollutant_srs_id = '5124', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '74884';
UPDATE pollutant SET pollutant_name = 'Acetaldehyde', last_inventory_year = NULL, pollutant_srs_id = '5280', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '75070';
UPDATE pollutant SET pollutant_name = 'Carbon Disulfide', last_inventory_year = NULL, pollutant_srs_id = '5348', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '75150';
UPDATE pollutant SET pollutant_name = 'Titanium Tetrachloride', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7550450';
UPDATE pollutant SET pollutant_name = 'Chloroacetic Acid', last_inventory_year = NULL, pollutant_srs_id = '7625', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '79118';
UPDATE pollutant SET pollutant_name = 'Dimethylcarbamoyl Chloride', last_inventory_year = NULL, pollutant_srs_id = '7864', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '79447';
UPDATE pollutant SET pollutant_name = 'Calcium Cyanamide', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '156627';
UPDATE pollutant SET pollutant_name = 'Benzo[e]Pyrene', last_inventory_year = NULL, pollutant_srs_id = '40618', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '192972';
UPDATE pollutant SET pollutant_name = 'Benzo(g,h,i)Fluoranthene', last_inventory_year = NULL, pollutant_srs_id = '524671880', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '203123';
UPDATE pollutant SET pollutant_name = 'Decachlorobiphenyl (PCB-209)', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '2051243';
UPDATE pollutant SET pollutant_name = 'Benzo[b]Fluoranthene', last_inventory_year = NULL, pollutant_srs_id = '40683', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '205992';
UPDATE pollutant SET pollutant_name = 'Benzo[k]Fluoranthene', last_inventory_year = NULL, pollutant_srs_id = '40709', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '207089';
UPDATE pollutant SET pollutant_name = 'Chrysene', last_inventory_year = NULL, pollutant_srs_id = '40733', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '218019';
UPDATE pollutant SET pollutant_name = 'PAH/POM - Unspecified', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '250';
UPDATE pollutant SET pollutant_name = 'Acenaphthene', last_inventory_year = NULL, pollutant_srs_id = '9555', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '83329';
UPDATE pollutant SET pollutant_name = 'Dibutyl Phthalate', last_inventory_year = NULL, pollutant_srs_id = '10025', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '84742';
UPDATE pollutant SET pollutant_name = 'Chlordane', last_inventory_year = NULL, pollutant_srs_id = '2683', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '57749';
UPDATE pollutant SET pollutant_name = '7,12-Dimethylbenz[a]Anthracene', last_inventory_year = NULL, pollutant_srs_id = '2733', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '57976';
UPDATE pollutant SET pollutant_name = '.gamma.-Hexachlorocyclohexane (Lindane)', last_inventory_year = NULL, pollutant_srs_id = '2923', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '58899';
UPDATE pollutant SET pollutant_name = 'Vinyl Bromide', last_inventory_year = NULL, pollutant_srs_id = '57448', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '593602';
UPDATE pollutant SET pollutant_name = 'Methylhydrazine', last_inventory_year = NULL, pollutant_srs_id = '3376', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '60344';
UPDATE pollutant SET pollutant_name = 'Acetamide', last_inventory_year = NULL, pollutant_srs_id = '3384', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '60355';
UPDATE pollutant SET pollutant_name = 'Nickel Refinery Dust', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '604';
UPDATE pollutant SET pollutant_name = 'Radionuclides (Radioactivity - Including Radon)', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'CURIE' where pollutant_code = '605';
UPDATE pollutant SET pollutant_name = 'Slagwool (Man-Made Fibers)', last_inventory_year = NULL, pollutant_srs_id = '649533', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '616';
UPDATE pollutant SET pollutant_name = 'Methyl Isocyanate', last_inventory_year = NULL, pollutant_srs_id = '63321', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '624839';
UPDATE pollutant SET pollutant_name = 'Aniline', last_inventory_year = NULL, pollutant_srs_id = '3632', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '62533';
UPDATE pollutant SET pollutant_name = 'Dichlorvos', last_inventory_year = NULL, pollutant_srs_id = '3681', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '62737';
UPDATE pollutant SET pollutant_name = 'N-Nitrosodimethylamine', last_inventory_year = NULL, pollutant_srs_id = '3707', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '62759';
UPDATE pollutant SET pollutant_name = 'Carbaryl', last_inventory_year = NULL, pollutant_srs_id = '3723', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '63252';
UPDATE pollutant SET pollutant_name = 'Diethyl Sulfate', last_inventory_year = NULL, pollutant_srs_id = '3889', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '64675';
UPDATE pollutant SET pollutant_name = '2,4,4''-Trichlorobiphenyl (PCB-28)', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7012375';
UPDATE pollutant SET pollutant_name = 'Benzene', last_inventory_year = NULL, pollutant_srs_id = '4754', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '71432';
UPDATE pollutant SET pollutant_name = 'Methoxychlor', last_inventory_year = NULL, pollutant_srs_id = '4903', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '72435';
UPDATE pollutant SET pollutant_name = 'Lead', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'CAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7439921';
UPDATE pollutant SET pollutant_name = 'Mercury', last_inventory_year = NULL, pollutant_srs_id = '149633', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7439976';
UPDATE pollutant SET pollutant_name = 'Arsenic', last_inventory_year = NULL, pollutant_srs_id = '149989', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7440382';
UPDATE pollutant SET pollutant_name = 'Cadmium', last_inventory_year = NULL, pollutant_srs_id = '150029', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7440439';
UPDATE pollutant SET pollutant_name = 'Hydrogen Cyanide', last_inventory_year = NULL, pollutant_srs_id = '5140', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '74908';
UPDATE pollutant SET pollutant_name = '7-PAH', last_inventory_year = 2005, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '75';
UPDATE pollutant SET pollutant_name = 'Vinyl Chloride', last_inventory_year = NULL, pollutant_srs_id = '5231', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '75014';
UPDATE pollutant SET pollutant_name = 'Methylene Chloride', last_inventory_year = NULL, pollutant_srs_id = '5306', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '75092';
UPDATE pollutant SET pollutant_name = 'Bromoform', last_inventory_year = NULL, pollutant_srs_id = '5447', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '75252';
UPDATE pollutant SET pollutant_name = 'Phosgene', last_inventory_year = NULL, pollutant_srs_id = '5587', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '75445';
UPDATE pollutant SET pollutant_name = '1,2-Propylenimine', last_inventory_year = NULL, pollutant_srs_id = '5652', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '75558';
UPDATE pollutant SET pollutant_name = 'Chromic Acid (VI)', last_inventory_year = 2022, pollutant_srs_id = '153213', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7738945';
UPDATE pollutant SET pollutant_name = 'Selenium', last_inventory_year = NULL, pollutant_srs_id = '154310', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7782492';
UPDATE pollutant SET pollutant_name = 'Ethylene Glycol Mono-Sec-Butyl Ether', last_inventory_year = NULL, pollutant_srs_id = '524671989', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7795917';
UPDATE pollutant SET pollutant_name = 'Ethyleneimine', last_inventory_year = NULL, pollutant_srs_id = '40279', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '151564';
UPDATE pollutant SET pollutant_name = 'Trifluralin', last_inventory_year = NULL, pollutant_srs_id = '89060', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '1582098';
UPDATE pollutant SET pollutant_name = '3,3''-Dimethoxybenzidine', last_inventory_year = NULL, pollutant_srs_id = '30924', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '119904';
UPDATE pollutant SET pollutant_name = '3,3''-Dimethylbenzidine', last_inventory_year = NULL, pollutant_srs_id = '30940', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '119937';
UPDATE pollutant SET pollutant_name = 'Sulfate Portion of PM2.5-PRI', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'OTH', pollutant_standard_uom_code = 'TON' where pollutant_code = 'SO4';
UPDATE pollutant SET pollutant_name = 'Polychlorinated Biphenyls', last_inventory_year = NULL, pollutant_srs_id = '85878', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '1336363';
UPDATE pollutant SET pollutant_name = '1,1,2,2-Tetrachloroethane', last_inventory_year = NULL, pollutant_srs_id = '7773', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '79345';
UPDATE pollutant SET pollutant_name = '2-Methylnaphthalene', last_inventory_year = NULL, pollutant_srs_id = '13524', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '91576';
UPDATE pollutant SET pollutant_name = '2,4-Dichlorophenoxy Acetic Acid', last_inventory_year = NULL, pollutant_srs_id = '15651', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '94757';
UPDATE pollutant SET pollutant_name = '4-Nitrophenol', last_inventory_year = NULL, pollutant_srs_id = '19117', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '100027';
UPDATE pollutant SET pollutant_name = 'Ethylene Dibromide', last_inventory_year = NULL, pollutant_srs_id = '23986', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '106934';
UPDATE pollutant SET pollutant_name = '2,4-Toluene Diisocyanate', last_inventory_year = NULL, pollutant_srs_id = '55939', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '584849';
UPDATE pollutant SET pollutant_name = 'p-Phenylenediamine', last_inventory_year = NULL, pollutant_srs_id = '23663', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '106503';
UPDATE pollutant SET pollutant_name = 'Hexamethylene Diisocyanate', last_inventory_year = NULL, pollutant_srs_id = '71209', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '822060';
UPDATE pollutant SET pollutant_name = '1-Methylnaphthalene', last_inventory_year = NULL, pollutant_srs_id = '12849', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '90120';
UPDATE pollutant SET pollutant_name = '2,4,5-Trichlorophenol', last_inventory_year = NULL, pollutant_srs_id = '16519', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '95954';
UPDATE pollutant SET pollutant_name = '4,4''-Methylenedianiline', last_inventory_year = NULL, pollutant_srs_id = '20347', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '101779';
UPDATE pollutant SET pollutant_name = 'Phosphine', last_inventory_year = NULL, pollutant_srs_id = '156588', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7803512';
UPDATE pollutant SET pollutant_name = 'Isophorone', last_inventory_year = NULL, pollutant_srs_id = '7187', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '78591';
UPDATE pollutant SET pollutant_name = 'o-Cresol', last_inventory_year = NULL, pollutant_srs_id = '16147', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '95487';
UPDATE pollutant SET pollutant_name = 'm-Cresol', last_inventory_year = NULL, pollutant_srs_id = '25064', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '108394';
UPDATE pollutant SET pollutant_name = 'Ethylidene Dichloride', last_inventory_year = NULL, pollutant_srs_id = '5520', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '75343';
UPDATE pollutant SET pollutant_name = 'Phosphorus', last_inventory_year = NULL, pollutant_srs_id = '153049', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7723140';
UPDATE pollutant SET pollutant_name = '1,1,2-Trichloroethane', last_inventory_year = NULL, pollutant_srs_id = '7518', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '79005';
UPDATE pollutant SET pollutant_name = 'Chromium', last_inventory_year = NULL, pollutant_srs_id = '150060', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7440473';
UPDATE pollutant SET pollutant_name = 'Triethylene glycol', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'OTH', pollutant_standard_uom_code = 'LB' where pollutant_code = '112276';
UPDATE pollutant SET pollutant_name = 'Epichlorohydrin', last_inventory_year = NULL, pollutant_srs_id = '23945', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '106898';
UPDATE pollutant SET pollutant_name = 'Carbon Tetrachloride', last_inventory_year = NULL, pollutant_srs_id = '2071', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '56235';
UPDATE pollutant SET pollutant_name = '2-Nitropropane', last_inventory_year = NULL, pollutant_srs_id = '7872', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '79469';
UPDATE pollutant SET pollutant_name = 'Acetophenone', last_inventory_year = NULL, pollutant_srs_id = '18333', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '98862';
UPDATE pollutant SET pollutant_name = 'Ethylene Dichloride', last_inventory_year = NULL, pollutant_srs_id = '24117', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '107062';
UPDATE pollutant SET pollutant_name = 'Methyl Chloroform', last_inventory_year = NULL, pollutant_srs_id = '4796', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '71556';
UPDATE pollutant SET pollutant_name = 'Acrylonitrile', last_inventory_year = NULL, pollutant_srs_id = '24182', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '107131';
UPDATE pollutant SET pollutant_name = 'Dimethyl Phthalate', last_inventory_year = NULL, pollutant_srs_id = '35295', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '131113';
UPDATE pollutant SET pollutant_name = 'o-Xylene', last_inventory_year = NULL, pollutant_srs_id = '16139', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '95476';
UPDATE pollutant SET pollutant_name = '1,2,4-Trichlorobenzene', last_inventory_year = NULL, pollutant_srs_id = '31435', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '120821';
UPDATE pollutant SET pollutant_name = 'Coke Oven Emissions', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '140';
UPDATE pollutant SET pollutant_name = 'Propylene Oxide', last_inventory_year = NULL, pollutant_srs_id = '5660', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '75569';
UPDATE pollutant SET pollutant_name = 'Trichloroethylene', last_inventory_year = NULL, pollutant_srs_id = '7526', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '79016';
UPDATE pollutant SET pollutant_name = 'Acrylic Acid', last_inventory_year = NULL, pollutant_srs_id = '7617', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '79107';
UPDATE pollutant SET pollutant_name = 'Manganese', last_inventory_year = NULL, pollutant_srs_id = '149625', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7439965';
UPDATE pollutant SET pollutant_name = 'Methyl Tert-Butyl Ether', last_inventory_year = NULL, pollutant_srs_id = '89870', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '1634044';
UPDATE pollutant SET pollutant_name = '1,3-Butadiene', last_inventory_year = NULL, pollutant_srs_id = '24042', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '106990';
UPDATE pollutant SET pollutant_name = 'Chlorobenzene', last_inventory_year = NULL, pollutant_srs_id = '25478', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '108907';
UPDATE pollutant SET pollutant_name = 'Chloroprene', last_inventory_year = NULL, pollutant_srs_id = '34090', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '126998';
UPDATE pollutant SET pollutant_name = 'Tetrachloroethylene', last_inventory_year = NULL, pollutant_srs_id = '34157', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '127184';
UPDATE pollutant SET pollutant_name = 'Phthalic Anhydride', last_inventory_year = NULL, pollutant_srs_id = '10355', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '85449';
UPDATE pollutant SET pollutant_name = 'Maleic Anhydride', last_inventory_year = NULL, pollutant_srs_id = '25015', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '108316';
UPDATE pollutant SET pollutant_name = 'Fluoranthene', last_inventory_year = NULL, pollutant_srs_id = '40691', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '206440';
UPDATE pollutant SET pollutant_name = 'N,N-Dimethylformamide', last_inventory_year = NULL, pollutant_srs_id = '4416', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '68122';
UPDATE pollutant SET pollutant_name = 'Ethyl Chloride', last_inventory_year = NULL, pollutant_srs_id = '5223', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '75003';
UPDATE pollutant SET pollutant_name = 'Ethylene Glycol', last_inventory_year = NULL, pollutant_srs_id = '24257', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '107211';
UPDATE pollutant SET pollutant_name = 'Methyl Chloride', last_inventory_year = NULL, pollutant_srs_id = '5116', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '74873';
UPDATE pollutant SET pollutant_name = 'Methyl Isobutyl Ketone', last_inventory_year = NULL, pollutant_srs_id = '24851', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '108101';
UPDATE pollutant SET pollutant_name = 'Xylenes (Mixed Isomers)', last_inventory_year = NULL, pollutant_srs_id = '84970', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '1330207';
UPDATE pollutant SET pollutant_name = 'Styrene', last_inventory_year = NULL, pollutant_srs_id = '19414', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '100425';
UPDATE pollutant SET pollutant_name = 'Hydrogen Fluoride', last_inventory_year = NULL, pollutant_srs_id = '152371', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7664393';
UPDATE pollutant SET pollutant_name = 'Methanol', last_inventory_year = NULL, pollutant_srs_id = '4283', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '67561';
UPDATE pollutant SET pollutant_name = 'Carbonyl Sulfide', last_inventory_year = NULL, pollutant_srs_id = '46508', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '463581';
UPDATE pollutant SET pollutant_name = 'Hydrochloric Acid', last_inventory_year = NULL, pollutant_srs_id = '152231', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '7647010';
UPDATE pollutant SET pollutant_name = 'Ammonia', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'CAP', pollutant_standard_uom_code = 'TON' where pollutant_code = 'NH3';
UPDATE pollutant SET pollutant_name = 'DDE (1,1-Dichloro-2,2-Bis(p-Chlorophenyl) Ethylene)', last_inventory_year = NULL, pollutant_srs_id = '4945', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '72559';
UPDATE pollutant SET pollutant_name = 'Nitrate portion of PM2.5-PRI', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'OTH', pollutant_standard_uom_code = 'TON' where pollutant_code = 'NO3';
UPDATE pollutant SET pollutant_name = 'Dibenzo(a,h)Anthracene', last_inventory_year = NULL, pollutant_srs_id = '', pollutant_type = 'HAP', pollutant_standard_uom_code = 'LB' where pollutant_code = '53703';

INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('57410', 'Phenytoin', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('60093', '4-Aminoazobenzene', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('70304', 'Hexachlorophene', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('72571', 'Trypan blue', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('76879', 'Triphenyltin hydroxide', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('77098', 'Phenolphthalein (3,3-Bis(4-hydroxyphenyl)phthalide)', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('79947', 'Tetrabromobisphenol A', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('80057', '4,4''-Isopropylidenediphenol', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('81492', '1-Amino-2,4-dibromoanthraquinone ', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('81889', 'C.I. Food Red 15 (Rhodamine B)', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('82280', '1-Amino-2-methylanthraquinone', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('86306', 'N-Nitrosodiphenylamine', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('90437', '2-Phenylphenol', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('90948', 'Michler’s ketone', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('91598', 'beta-Naphthylamine (2-Naphthalenamine)', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('94360', 'Benzoyl peroxide', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('97234', 'Dichlorophene ', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('97563', 'C.I. Solvent Yellow 3', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('101611', '4,4''-Methylenebis(N,N-dimethyl)benzenamine (4,4''-Methylenebis[N,N-dimethylaniline])', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('101804', '4,4''-Diaminodiphenyl ether', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('115322', 'Dicofol', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('117793', '2-Aminoanthraquinone', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('122394', 'Diphenylamine', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('128665', 'C.I. Vat Yellow 4', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('132274', 'Sodium o-phenylphenoxide', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('134327', 'alpha-Naphthylamine (1-Naphthalenamine)', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('139651', '4,4''-Thiodianiline', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('156105', 'p-Nitrosodiphenylamine', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('492808', 'C.I. Solvent Yellow 34 (Auramine)', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('569642', 'C.I. Basic Green 4 (Malachite green)', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('612828', '3,3''-Dimethylbenzidine dihydrochloride', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('612839', '3,3''-Dichlorobenzidine dihydrochloride', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('639587', 'Triphenyltin chloride', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('842079', 'C.I. Solvent Yellow 14', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('957517', 'Diphenamid', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('989388', 'C.I. Basic Red 1', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('1163195', 'Decabromodiphenyl oxide', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('1335871', 'Hexachloronaphthalene', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('1836755', 'Nitrofen', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('1937377', 'C.I. Direct Black 38', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('2234131', 'Octachloronaphthalene', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('2602462', 'C.I. Direct Blue 6', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('2832408', 'C.I. Disperse Yellow 3', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('3118976', 'C.I. Solvent Orange 7', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('3383968', 'Temephos', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('3761533', 'C.I. Food Red 5', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('4680788', 'C.I. Acid Green 3', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('6459945', 'C.I. Acid Red 114', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('13356086', 'Fenbutatin oxide', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('13684565', 'Desmedipham', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('16071866', 'C.I. Direct Brown 95', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('20325400', '3,3''-Dimethoxybenzidine dihydrochloride ', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('26002802', 'Phenothrin ', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('28407376', 'C.I. Direct Blue 218', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('33089611', 'Amitraz', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('35367385', 'Diflubenzuron', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('39515418', 'Fenpropathrin', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('41766750', '3,3''-Dimethylbenzidine dihydrofluoride', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('42874033', 'Oxyfluorfen', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('51338273', 'Diclofop methyl', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('51630581', 'Fenvalerate', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('52645531', 'Permethrin', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('60168889', 'Fenarimol ', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('62476599', 'Acifluorfen, sodium salt ', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('64969342', '3,3''-Dichlorobenzidine sulfate', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('66441234', 'Fenoxaprop-ethyl ', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('67485294', 'Hydramethylnon', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('68085858', 'Cyhalothrin ', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('68359375', 'Cyfluthrin', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('69409945', 'Fluvalinate', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('72178020', 'Fomesafen ', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('72490018', 'Fenoxycarb ', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('76578148', 'Quizalofop-ethyl ', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('77501634', 'Lactofen ', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('82657043', 'Bifenthrin', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('111984099', '3,3''-Dimethoxybenzidine monohydrochloride', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('N575', 'Polybrominated biphenyls (PBBs)', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('N874', 'Warfarin and salts', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('5385751', 'Dibenzo[a,e]fluoranthene', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('335933', 'Silver perfluorooctanoate', NULL, '', 'PFAS', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('375735', 'Perfluorobutanesulfonic acid', NULL, '', 'PFAS', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('507631', 'Perfluorooctyl iodide', NULL, '', 'PFAS', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('2395008', 'Potassium perfluorooctanoate', NULL, '', 'PFAS', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('29420493', 'Potassium perfluorobutanesulfonate', NULL, '', 'PFAS', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('45187153', 'Perfluorobutanesulfonate', NULL, '', 'PFAS', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('65104452', '2-Propenoic acid, 2-methyl-, 3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,12-heneicosafluorodode...', NULL, '', 'PFAS', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('203743037', '2-Propenoic acid, 2-methyl-, hexadecyl ester, polymers with 2-hydroxyethyl methacrylate, .gamma.-…', NULL, '', 'PFAS', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('319846', '.alpha.-Hexachlorocyclohexane', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('319857', '.beta.-Hexachlorocyclohexane', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('319868', '.delta.-Hexachlorocyclohexane', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('608731', '1,2,3,4,5,6-Hexachlorocyclohexane (technical) (Mixed Isomers)', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('6108107', '.epsilon.-Hexachlorocyclohexane', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('6108118', '.zeta.-Hexachlorocyclohexane', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('6108129', '.eta.-Hexachlorocyclohexane', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('6108130', '.theta.-Hexachlorocyclohexane', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('94111', '2,4-D isopropyl ester', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('94804', '2,4-D butyl ester', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('1320189', '2,4-D propylene glycol butyl ether ester (2,4-D 2-butoxymethylethyl ester)', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('1928434', '2,4-D 2-ethylhexyl ester', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('1929733', '2,4-D butoxyethyl ester', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('2008391', '2,4-D dimethylamine salt', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('2702729', '2,4-D sodium salt', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('2971382', '2,4-D chlorocrotyl ester', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('5742176', '2,4-D isopropylamine salt', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('5742198', '2,4-D diethanolamine salt', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('32341803', '2,4-D triisopropanolammonium salt', NULL, '', 'HAP', 'LB', NULL);
INSERT INTO pollutant (pollutant_code, pollutant_name, pollutant_cas_id, pollutant_srs_id, pollutant_type, pollutant_standard_uom_code, last_inventory_year) VALUES ('53404378', '2,4-D 2-ethyl-4-methylpentyl ester', NULL, '', 'HAP', 'LB', NULL);

INSERT INTO point_source_scc_code (code, last_inventory_year, fuel_use_required, calculation_material_code, fuel_use_types, short_name, scc_level_one, scc_level_two, scc_level_three, scc_level_four, sector, monthly_reporting) VALUES ('30500248', NULL, false, NULL, NULL, NULL, 'Industrial Processes', 'Mineral Products', 'Asphalt Concrete', 'Batch Mix Plant: Hot Elevators, Screens, Bins, Mixer & Propane Rot Dryer', 'Industrial Processes - NEC', false);
INSERT INTO point_source_scc_code (code, last_inventory_year, fuel_use_required, calculation_material_code, fuel_use_types, short_name, scc_level_one, scc_level_two, scc_level_three, scc_level_four, sector, monthly_reporting) VALUES ('30500254', NULL, false, NULL, NULL, NULL, 'Industrial Processes', 'Mineral Products', 'Asphalt Concrete', 'Drum Mix Plant: Rotary Drum Dryer/Mixer, Propane-Fired', 'Industrial Processes - NEC', false);
INSERT INTO point_source_scc_code (code, last_inventory_year, fuel_use_required, calculation_material_code, fuel_use_types, short_name, scc_level_one, scc_level_two, scc_level_three, scc_level_four, sector, monthly_reporting) VALUES ('30500264', NULL, false, NULL, NULL, NULL, 'Industrial Processes', 'Mineral Products', 'Asphalt Concrete', 'Drum Mix Plant: Rotary Drum Dryer / Mixer, Propane, Parallel Flow', 'Industrial Processes - NEC', false);
INSERT INTO point_source_scc_code (code, last_inventory_year, fuel_use_required, calculation_material_code, fuel_use_types, short_name, scc_level_one, scc_level_two, scc_level_three, scc_level_four, sector, monthly_reporting) VALUES ('30500265', NULL, false, NULL, NULL, NULL, 'Industrial Processes', 'Mineral Products', 'Asphalt Concrete', 'Drum Mix Plant: Rotary Drum Dryer / Mixer, Propane, Counterflow', 'Industrial Processes - NEC', false);
